Cargo.lock
Cargo.toml
OSlibs/crash_reports.rs
OSlibs/win/seh.c
build.rs
iguana/exchanges/etomicswap/Cargo.toml
iguana/exchanges/mm2.rs

By using a C helper with the `__try`/`__except` pair in it we're able to catch the segmentation faults and print the stack trace.
It seems that the next step should be running everything from a Rust binary in order to wrap the MarketMaker code in the Rust fault-catching machinery, and for `cargo test` to just work.

Catching segmentation faults on Windows, proof of concept

---

Cargo.lock
mm2src/coins/Cargo.toml

Removes the `tokio-uds 0.1.7` dependency, #296.

Unsubscribe from web3/ipc

---

Cargo.lock
azure-pipelines-job.yml
mm2src/coins/Cargo.toml
mm2src/coins/eth.rs
mm2src/coins/eth/web3_transport.rs
mm2src/coins/lp_coins.rs
mm2src/coins/utxo/rpc_clients.rs
mm2src/common/common.rs
mm2src/mm2_tests.rs

This allows to get rid of all default Rust Web3 features.
Use getTransactionCount to get nonce and validate that it was increased.
#196 #306

Use our own Web3 transport. Allow to set ETH nodes URL from config.

---

Cargo.lock
js/Dockerfile
mm2src/coins/Cargo.toml
mm2src/coins/eth.rs
mm2src/coins/lp_coins.rs
mm2src/coins/utxo.rs
mm2src/coins/utxo/rpc_clients.rs
mm2src/common/common.rs
mm2src/common/executor.rs
mm2src/lp_native_dex.rs
mm2src/peers/peers.rs
mm2src/peers/peers_tests.rs

@artemii235 , I'm trying to use async/await futures for the portable version of `CORE.spawn`,
for reasons of compatibility with the future of futures and code simplification.
As a part of it I changed some of the Electrum code in `rpc_clients` to use the async/await `spawn`.
Would like you to take a look, maybe you'll spot something I've missed in the logic during refactorings.

Portability WIP

---

Cargo.lock
Cargo.toml
mm2src/coins/eth.rs
mm2src/coins/lp_coins.rs
mm2src/coins/test_coin.rs
mm2src/coins/utxo.rs
mm2src/common/Cargo.toml
mm2src/common/common.rs
mm2src/common/mm_number.rs
mm2src/lp_native_dex.rs
mm2src/lp_ordermatch.rs
mm2src/lp_swap/maker_swap.rs
mm2src/lp_swap/taker_swap.rs
mm2src/mm2_tests.rs
mm2src/ordermatch_tests.rs

The implementation is backwards compatible with other nodes that use BigDecimal type only.
Rational amounts are displayed as separate fields in orderbook and order_status calls.

Allow to set rational numbers as orders price and volume #537

---

CMakeLists.txt
Dockerfile
README.md
js/Dockerfile

We didn't had a stable Rust version for a while: some of the recommended versions where too outdated for the fresh asynchronous code while others had issues with RLS being unavailble for the given version, one of the platforms not being supported for the given version, etc.
Rust 1.41 [relaxed the orphan rule](https://blog.rust-lang.org/2020/01/30/Rust-1.41.0.html#relaxed-restrictions-when-implementing-traits), which I think is of major importance for API design, and the time of release is also a good time to pin the Rust nightly version as it minimizes the likehood of nightly issues.
(If the motion is approved then I can bump the mobile version as well).

Recommend Rust 2020-02-01 (1.41)

---

Cargo.lock
Cargo.toml
azure-pipelines-build-stage-job.yml
azure-pipelines-job.yml
azure-pipelines-release-stage-job.yml
azure-pipelines.yml
mm2src/common/Cargo.toml
mm2src/common/common.rs

Print items with their instruction pointers to backtrace even if symbolication fails in order to be able to symbolicate the trace using debug symbols that are also published with release.
Also print load addresses of mm2 binary segments on Linux and MacOS.
Windows debug symbols stripping is not required at least now because it's binary size is much less than Linux/MacOS.

Setup automatic Github release publishing on mm2 branch.

---

Cargo.lock
mm2src/coins/utxo/rpc_clients.rs
mm2src/common/Cargo.toml

@artemii235 
This fixes the build script after a `cargo update`,
though I am still having problems with
```
Compiling coins v0.1.0 (C:\spool\synced\komodo\SuperNET\mm2src\coins)
error[E0308]: mismatched types
--> mm2src\coins\utxo\rpc_clients.rs:708:9
|
708 |         addr,
|         ^^^^
|         |
|         expected struct `std::string::String`, found enum `std::net::SocketAddr`
|         help: try using a conversion method: `addr: addr.to_string()`
error: aborting due to previous error
```

Add access to ISATTY for build script

---

mm2src/coins/utxo/utxo_tests.rs
mm2src/common/for_tests.rs
mm2src/common/mm_metrics.rs
mm2src/mm2_tests.rs
mm2src/ordermatch_tests.rs

* Replace the coins with RICK, MORTY, ETH in each of the tests
* Replace testN.cipig.net with electrumN.cipig.net urls and corresponding 10022, 10024, 10025 ports with 10017, 10018
* Change the test_search_for_swap_tx_spend_electrum_was_spent and test_search_for_swap_tx_spend_electrum_was_refunded tests: replace ETOMIC to RICK swaps

Remove ETOMIC, PIZZA and BEER coins #657

---

Cargo.lock
mm2src/gossipsub/src/behaviour.rs
mm2src/gossipsub/src/behaviour/tests.rs
mm2src/gossipsub/src/handler.rs
mm2src/gossipsub/src/protocol.rs
mm2src/gossipsub/src/rpc.proto
mm2src/gossipsub/tests/smoke.rs
mm2src/lp_network.rs
mm2src/lp_ordermatch.rs
mm2src/mm2_libp2p/Cargo.toml
mm2src/mm2_libp2p/src/adex_ping.rs
mm2src/mm2_libp2p/src/atomicdex_behaviour.rs
mm2src/mm2_libp2p/src/lib.rs
mm2src/mm2_libp2p/src/peers_exchange.rs
mm2src/mm2_libp2p/src/request_response.rs
mm2src/mm2_tests.rs
mm2src/ordermatch_tests.rs

Some aspects are omitted intentionally to be implemented later, e.g.:
1. It's worth to sign the announced addresses messages.
1. Might make sense to "forget" the known peer or at least reduce it's "score" in case we failed to connect to announced address.
1. Need to save discovered peers state to DB and use it on restart.
1. Implement more methods of initial nodes discovery/bootstrap. Maybe borrow some concepts from bitcoin (https://developer.bitcoin.org/devguide/p2p_network.html#peer-discovery), also notable: https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md

Add peer discovery/exchange working on top of request response also using reserved gossipsub topic.

---

mm2src/lp_swap/taker_swap.rs

* max_taker_vol RPC handler will return 0 if calc_max_taker_vol returns an error
* max_taker_vol_from_available return an error instead of 0

Fix max_taker_vol_from_available

---

mm2src/lp_ordermatch/best_orders.rs
mm2src/mm2_tests.rs

Use correct direction of the pair for best_orders sell action.

---

Cargo.lock
azure-pipelines-build-stage-job.yml
azure-pipelines.yml
etomic_build/client/buy_ONE_ANOTHER
etomic_build/client/enable_ADEX
etomic_build/client/enable_BNB
etomic_build/client/enable_BNBT
mm2src/coins/eth.rs
mm2src/coins/eth/eth_tests.rs

Minor fixes for Binance Smart Chain/BEP20 integration.

---

mm2src/coins/eth.rs
mm2src/coins/eth/eth_tests.rs
mm2src/coins/lp_coins.rs
mm2src/coins/qrc20.rs
mm2src/coins/qrc20/qrc20_tests.rs
mm2src/coins/test_coin.rs
mm2src/coins/utxo/qtum.rs
mm2src/coins/utxo/utxo_common.rs
mm2src/coins/utxo/utxo_standard.rs
mm2src/coins/utxo/utxo_tests.rs
mm2src/common/big_int_str.rs
mm2src/common/build.rs
mm2src/common/mm_number.rs
mm2src/docker_tests.rs
mm2src/lp_ordermatch.rs
mm2src/lp_ordermatch/orderbook_rpc.rs
mm2src/lp_swap.rs
mm2src/lp_swap/maker_swap.rs
mm2src/lp_swap/taker_swap.rs
mm2src/mm2.rs
mm2src/mm2_tests.rs
mm2src/mm2_tests/structs.rs
mm2src/ordermatch_tests.rs
mm2src/rpc.rs

Add more info to orderbook response for charts. Display UTXO fee to spend the payment in trade_preimage response.
#859 #872

orderbook and trade_preimage RPC improvements.

---

mm2src/lp_ordermatch.rs
mm2src/mm2_libp2p/src/atomicdex_behaviour/tests.rs
mm2src/mm2_libp2p/src/request_response.rs

Do not hold orderbook lock during GetOrderbook request.
#910

Set explicit 10 seconds timeout for P2P requests in our behavior.

---

mm2src/coins/utxo.rs
mm2src/mm2_tests.rs

Make SIGHASH_FORKID configurable with coins file

---

mm2src/database.rs
mm2src/database/stats_swaps.rs

It will make DB processing easier since aggregators mostly do not differ the coins by different platforms.
#909

Split maker and taker coin in stats DB to ticker and platform.

---

mm2src/coins/eth.rs
mm2src/coins/lp_coins.rs
mm2src/coins/qrc20.rs
mm2src/coins/test_coin.rs
mm2src/coins/utxo/qtum.rs
mm2src/coins/utxo/utxo_standard.rs
mm2src/lp_ordermatch.rs
mm2src/lp_ordermatch/best_orders.rs
mm2src/lp_ordermatch/orderbook_depth.rs
mm2src/lp_ordermatch/orderbook_rpc.rs
mm2src/lp_swap.rs
mm2src/mm2_tests.rs

wallet-only mode

---

Cargo.lock
mm2src/common/Cargo.toml
mm2src/common/common.rs
mm2src/common/for_tests.rs
mm2src/common/log/wasm_log.rs
mm2src/common/patterns/state_machine.rs
mm2src/common/transport/wasm_ws.rs

* Add WebSocket transport working in Wasm
* Add StateMachine pattern

Implement WebSocket transport

---

mm2src/coins/lp_coins.rs
mm2src/docker_tests.rs
mm2src/docker_tests/qrc20_tests.rs
mm2src/lp_ordermatch.rs
mm2src/lp_swap/check_balance.rs
mm2src/lp_swap/maker_swap.rs
mm2src/lp_swap/taker_swap.rs
mm2src/lp_swap/trade_preimage.rs
mm2src/mm2_tests/structs.rs

* GenerateTxError::OutputValueLessThanDust converts to TradePreimageError::InternalError the value is upper bound
* Fix invalid required field in NotSufficientBalance error generated by calc_max_maker_vol

Ensure that trade_preimage will not succeed on input that will fail on buy/sell/setprice

---

mm2src/coins/eth.rs
mm2src/coins/lp_coins.rs
mm2src/coins/qrc20.rs
mm2src/lp_swap/check_balance.rs
mm2src/lp_swap/trade_preimage.rs
mm2src/mm2_tests.rs
mm2src/mm2_tests/structs.rs

I decided to refactor a bit the `WithdrawError::AmountTooLow` error type when filling out the docs.
* Rename `WithdrawError::AmountIsTooSmall` to `WithdrawError::AmountTooLow`
* Add the 'threshold' filed to `WithdrawError::AmountTooLow`
* Fix error description of `TradePreimageRpcError::VolumeTooLow`

Refactor WithdrawError::AmountTooLow

---

mm2src/lp_ordermatch.rs
mm2src/lp_ordermatch/new_protocol.rs

Fix P2P messages backwards compatibilty in update_maker_order PR

---

mm2src/coins/eth.rs
mm2src/coins/lp_coins.rs
mm2src/coins/qrc20.rs
mm2src/coins/qrc20/history.rs
mm2src/coins/qrc20/qrc20_tests.rs
mm2src/coins/utxo.rs
mm2src/coins/utxo/qtum.rs
mm2src/coins/utxo/utxo_common.rs
mm2src/coins/utxo/utxo_standard.rs
mm2src/coins/utxo/utxo_tests.rs
mm2src/coins/z_coin.rs

* Add 'kmd_rewards' to TransactionDetails returning from withdraw, my_tx_history

Return KMD rewards amount for all KMD txs #874

---

mm2src/coins/utxo/utxo_tests.rs
mm2src/mm2_bitcoin/rpc/src/v1/types/script.rs
mm2src/mm2_bitcoin/rpc/src/v1/types/transaction.rs

Support FIRO Lelantus verbose tx #983

---

mm2src/coins/qrc20.rs
mm2src/coins/qrc20/qrc20_tests.rs
mm2src/coins/qrc20/swap.rs

Add QRC20_PAYMENT_GAS_LIMIT of 200000 #980

---

mm2src/lp_ordermatch.rs
mm2src/mm2_tests.rs

Fix the duplicates in best_orders response.

---

mm2src/docker_tests.rs
mm2src/lp_swap/taker_swap.rs
mm2src/mm2_tests/structs.rs

Add coin field to max_taker_vol response #991

---

mm2src/coins/lp_coins.rs
mm2src/docker_tests.rs
mm2src/lp_ordermatch.rs
mm2src/lp_swap.rs

Cancel the kickstarted order immediately if balance is not sufficient.

---

Cargo.lock
mm2src/coins/Cargo.toml
mm2src/coins/eth.rs
mm2src/coins/lp_coins.rs
mm2src/coins/qrc20.rs
mm2src/coins/test_coin.rs
mm2src/coins/utxo.rs
mm2src/coins/utxo/qtum.rs
mm2src/coins/utxo/slp.rs
mm2src/coins/utxo/utxo_common.rs
mm2src/coins/utxo/utxo_standard.rs
mm2src/coins/utxo/utxo_tests.rs
mm2src/coins/z_coin.rs
mm2src/docker_tests/qrc20_tests.rs
mm2src/lp_ordermatch.rs
mm2src/lp_ordermatch/best_orders.rs
mm2src/lp_ordermatch/new_protocol.rs
mm2src/lp_ordermatch/orderbook_rpc.rs
mm2src/mm2_tests.rs
mm2src/mm2_tests/structs.rs
mm2src/ordermatch_tests.rs

This PR prevents order matching between new nodes and older nodes for coins that segwit is enabled for in the newer nodes.

segwit backward compatibility

---

mm2src/coins/utxo.rs
mm2src/coins/utxo/rpc_clients.rs
mm2src/coins/utxo/utxo_common.rs
mm2src/coins/utxo/utxo_tests.rs
mm2src/mm2_bitcoin/keys/src/address.rs

Hotfix for withdraw to p2sh addresses

---

mm2src/docker_tests/qrc20_tests.rs
mm2src/lp_ordermatch.rs
mm2src/lp_ordermatch/best_orders.rs
mm2src/lp_ordermatch/new_protocol.rs
mm2src/lp_ordermatch/orderbook_rpc.rs
mm2src/mm2_tests.rs
mm2src/ordermatch_tests.rs

fixes #1044
This fixes pair trie to be consistent across old and new nodes preventing inconsistent behavior in keeping orders alive

Fix orders disappearing from orderbook

---

Cargo.lock
mm2src/coins/utxo.rs
mm2src/mm2_bitcoin/script/Cargo.toml
mm2src/mm2_bitcoin/script/src/lib.rs
mm2src/mm2_bitcoin/script/src/sign.rs

as found by @cipig [LCC](https://github.com/KomodoPlatform/coins/blob/c8c728ba21c6f8ac78cbd67bab3ee89d3d33643c/coins#L1988) withdraws are not working after this [PR](https://github.com/KomodoPlatform/atomicDEX-API/pull/1040), as a fix a new field `"signature_version": "base"` should be added to [LCC](https://github.com/KomodoPlatform/coins/blob/c8c728ba21c6f8ac78cbd67bab3ee89d3d33643c/coins#L1988) config. for any coin that needs a default `signature_version`, this field can be used with the parameters `base`, `witness_v0` or `fork_id`. @cipig can you please test if this is working now after adding this new field to your [LCC](https://github.com/KomodoPlatform/coins/blob/c8c728ba21c6f8ac78cbd67bab3ee89d3d33643c/coins#L1988) config?

Add signature_version to coin configuration

---

mm2src/lp_ordermatch.rs
mm2src/lp_ordermatch/my_orders_storage.rs
mm2src/ordermatch_tests.rs

fixes https://github.com/KomodoPlatform/atomicDEX-API/issues/941#issuecomment-918023912
@Milerius if this doesn't fix the memory leak then you can lower `TRIE_ORDER_HISTORY_TIMEOUT `https://github.com/KomodoPlatform/atomicDEX-API/blob/3402e6defc08092d3bf602da71bae81d37984d29/mm2src/lp_ordermatch.rs#L107 to less than 30 seconds maybe 15 or something to test if it's from `insert_new_diff` https://github.com/KomodoPlatform/atomicDEX-API/blob/3402e6defc08092d3bf602da71bae81d37984d29/mm2src/lp_ordermatch.rs#L2215
as it can be the other reason for the memory leak.

update_maker_order memory leak fix

---

mm2src/coins/eth.rs

This pr can be tested through this GUI update: https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1303
@tonymorony this required a full test on ETH to be sure that nothing is broken, you can use ETHR for the testing.
`gas_station_url` for ETHR can be used for chargeless testing.
I will also sync this with mm2.1 after the merge of #1075 in order to match UTXO's coins.

enhancements(eth): remove unused fields and support alias name

---

azure-pipelines-build-stage-job.yml

Upload release library to nightly server during CI build.

---

mm2src/coins/eth.rs
mm2src/coins/eth/web3_transport.rs
mm2src/coins/utxo/rpc_clients.rs
mm2src/common/common.rs
mm2src/common/executor/native_executor.rs
mm2src/common/executor/wasm_executor.rs
mm2src/common/for_tests.rs
mm2src/common/grpc_web.rs
mm2src/common/ip_addr.rs
mm2src/common/transport/native_http.rs
mm2src/common/transport/transport.rs
mm2src/common/transport/wasm_http.rs
mm2src/common/wio.rs
mm2src/lp_ordermatch/simple_market_maker.rs

* Add SlurpError
* Refactor slurp_req, slurp_url so they return SlurpResult
* Replace slurp functions into native/wasm common::transport
* Replace native executor mod into native_executor.rs
* Rename executor.rs into wasm_executor.rs
* Replace wio mod from common.rs into wio.rs

Slurp refactoring #914

---

mm2src/coins/utxo.rs

fixes #913
Now when server.version request times out due to a connection error the electrum client will retry to get the server version every 60 seconds without dropping the connection. Not sure if this is the best way to do this or should we have a maximum number for the retries @artemii235? are 60 seconds also a good delay for this?

Hotfix: skip remove_server on server.version time out

---

mm2src/coins/utxo/utxo_common.rs

fixes https://github.com/KomodoPlatform/atomicDEX-API/pull/1133#issuecomment-975963212
I can see that the `generate_transaction` fn is changed to `UtxoTxBuilder` in the dev branch so maybe I should do the same fix in the [Lightning Network Channels PR](https://github.com/KomodoPlatform/atomicDEX-API/pull/1133)
Note that for legacy transactions virtual bytes are equal to actual bytes.

Hotfix: Use virtual bytes to calculate correct tx fees for Segwit UTXO generate_transaction 

---

Cargo.lock
Cargo.toml
mm2src/common/Cargo.toml
mm2src/common/log.rs
mm2src/common/mm_ctx.rs
mm2src/common/shared_ref_counter/Cargo.toml
mm2src/common/shared_ref_counter/src/disable.rs
mm2src/common/shared_ref_counter/src/enable.rs
mm2src/common/shared_ref_counter/src/lib.rs
mm2src/lp_native_dex.rs
mm2src/lp_ordermatch.rs
mm2src/ordermatch_tests.rs

* Add `SharedRc` and `WeakRc` that can be used to debug hanging pointers
* Move `MmCtx::stop` to `MmArc::stop`
* Replace `Arc<MmCtx>` with `SharedRc<MmCtx>`
To run mm2 with pointer tracker, run
```
cargo build --feature track-ctx-pointer
```
We also can add a test that checks if all `MmArc` pointers are released in 30s.

Fix hanging pointers #1158

---

mm2src/coins/lp_coins.rs
mm2src/coins/qrc20.rs
mm2src/coins/qrc20/qrc20_tests.rs
mm2src/coins/utxo.rs
mm2src/coins/utxo/utxo_common.rs
mm2src/coins/utxo/utxo_tests.rs
mm2src/docker_tests.rs

close #901 
Before opening the pr I did the following checks:
- Run `utxo_tests` test suite
- Run `qrc20_tests` test suite
- Using grep to verify occurrences of `Fixed(` into mm2src folder
ps: If the code specific code related to DOGE need to be removed, coins configuration need to also be updated, please let me know the value per KB that would suits DOGE transaction (txfee) before I can remove the DOGE specific code!

feat(utxo_fees): replace fixed fee with fee per kb

---

mm2src/lp_ordermatch.rs
mm2src/lp_ordermatch/my_orders_storage.rs
mm2src/lp_ordermatch/simple_market_maker.rs
mm2src/mm2_tests.rs
mm2src/ordermatch_tests.rs

Use parking lot mutex for maker orders

---

mm2src/lp_network.rs
mm2src/lp_ordermatch.rs
mm2src/lp_ordermatch/best_orders.rs
mm2src/lp_ordermatch/orderbook_depth.rs
mm2src/lp_ordermatch/orderbook_rpc.rs
mm2src/lp_stats.rs
mm2src/lp_swap/maker_swap.rs
mm2src/lp_swap/taker_swap.rs
mm2src/ordermatch_tests.rs
mm2src/rpc/lp_commands.rs

Fix orders "leak" due to race condition.

---

mm2src/lp_swap/recreate_swap_data.rs

I found an error while trying to generate Taker swap data of the `8f285eec-7cae-4d9e-bada-0dfe181e6baa` swap.

Fix recreating Taker swap data

---

etomic_build/client/enable_tBCH
mm2src/coins/utxo/rpc_clients.rs

Avoid log spam and malfunctioning electrums excessive reconnects #1193 #1161.

---

mm2src/coins/lightning.rs
mm2src/coins/lp_coins.rs
mm2src/coins/qrc20.rs
mm2src/coins/qrc20/qrc20_tests.rs
mm2src/coins/utxo.rs
mm2src/coins/utxo/bch.rs
mm2src/coins/utxo/qtum.rs
mm2src/coins/utxo/qtum_delegation.rs
mm2src/coins/utxo/utxo_builder/mod.rs
mm2src/coins/utxo/utxo_builder/utxo_arc_builder.rs
mm2src/coins/utxo/utxo_builder/utxo_coin_builder.rs
mm2src/coins/utxo/utxo_common.rs
mm2src/coins/utxo/utxo_standard.rs
mm2src/coins/utxo/utxo_tests.rs
mm2src/coins/utxo/utxo_withdraw.rs
mm2src/coins/z_coin.rs
mm2src/coins_activation/src/utxo_activation/init_qtum_activation.rs
mm2src/docker_tests/docker_tests_common.rs
mm2src/docker_tests/qrc20_tests.rs

* Add `QtumCoinBuilder` and `QtumCoinWithIguanaPrivKeyBuilder` that override `check_utxo_maturity`
* Add `UtxoCommonOps::list_all_unspent_ordered` that behaves as `UtxoCommonOps::list_unspent_ordered` before
* `UtxoCommonOps::list_unspent_ordered` checks the `check_utxo_maturity` flag to use either `list_all_unspent_ordered` or `list_mature_unspent_ordered`
* Rename `UtxoCommonOps::ordered_mature_unspents` to `UtxoCommonOps::list_mature_unspent_ordered`

Add check_utxo_maturity to electrum/enable RPC call

---

mm2src/coins/utxo/rpc_clients.rs
mm2src/coins/utxo/utxo_tests.rs

Fixes https://github.com/KomodoPlatform/atomicDEX-API/issues/1196

Expect larger integers on blockchain.scripthash.get_balance

---

mm2src/coins/eth.rs
mm2src/coins/lightning.rs
mm2src/coins/lp_coins.rs
mm2src/coins/qrc20.rs
mm2src/coins/solana.rs
mm2src/coins/solana/spl.rs
mm2src/coins/test_coin.rs
mm2src/coins/utxo.rs
mm2src/coins/utxo/bch.rs
mm2src/coins/utxo/qtum.rs
mm2src/coins/utxo/slp.rs
mm2src/coins/utxo/utxo_common.rs
mm2src/coins/utxo/utxo_standard.rs
mm2src/coins/z_coin.rs
mm2src/mm2_tests.rs
mm2src/mm2_tests/structs.rs
mm2src/rpc/dispatcher/dispatcher.rs

Add func `get_raw_transaction` for all protocols that implemented this feature.
protocols:
- `eth`
- `qrc20`
- `utxo`
- `bch`
- `lightning`
- `solna` it should be implemented in the future
also add unit test to check the result of this func.

Add RPC call to get raw transaction encoded in hex

---

Cargo.toml
mm2src/docker_tests/swaps_confs_settings_sync_tests.rs
mm2src/lp_swap.rs
mm2src/mm2.rs

This PR allows you to provide custom payment_locktime from either CLI or MM2.json. The property name should be `payment_locktime`. When it's not provided or invalid type, it will be processed as 900 seconds.
Example MM2.json:
```json
{
"payment_locktime": 1453
}
```
Example Command-Line
```
mm2 "{ \"payment_locktime\": 1453 }"
```
closes #1246
Signed-off-by: ozkanonur <work@onurozkan.dev>

provide custom swap locktime functionality

---

mm2src/coins/utxo/utxo_sql_block_header_storage.rs

https://github.com/KomodoPlatform/atomicDEX-API/blob/9c79755a19e3e4a6e0e5515b0586b9be3c9abf8b/mm2src/coins/utxo.rs#L1101
`blocks_limit_to_check` in coins config has to be equal to or greater than the number of blocks needed before the chain is safe from reorganization (e.g. 6 blocks for BTC) to avoid invalid SPV proofs in case of block reorganization.

Update block headers in DB in case of a chain reorganization

---

Dockerfile.dev-release
azure-pipelines-build-stage-job.yml

fixes #1253
Signed-off-by: Onur Özkan <work@onurozkan.dev>

[r2r] continuously push for playground nodes

---

Cargo.lock
deny.toml
mm2src/common/Cargo.toml

Also disabled default features for log4rs, which reduced the number of deps a bit.
@sergeyboyko0791 @ozkanonur @shamardy Requesting your review mostly for ACK.

Temporary ignore RUSTSEC-2020-0071 (time crate potential segfault).

---

CONTRIBUTING.md
Cargo.lock
azure-pipelines-lint-stage-job.yml
mm2src/coins/Cargo.toml
mm2src/common/Cargo.toml
mm2src/mm2_core/Cargo.toml
mm2src/mm2_db/Cargo.toml
mm2src/mm2_libp2p/Cargo.toml
mm2src/mm2_main/Cargo.toml

A few notes:
- If `cargo udeps` fails on all CI agents (all operating systems), this means that the dependencies shown in the output should either be removed or are used in testing/wasm/features only, in this case these dependencies should be moved to the right target (e.g. `[dev-dependencies]`, `[target.'cfg(target_arch = "wasm32")'.dependencies]`).
- If `cargo udeps` fails on all CI agents (all operating systems) except one, then this is a dependency for this certain OS, in this case these dependencies should be moved to the right target (e.g. `[target.'cfg(windows)'.dependencies]`).

Remove unused dependencies, add unused dependencies check step to CI

---

mm2src/coins/utxo/utxo_tests.rs

The task is to send a QTUM from one address to the same and have multiple identical outputs with amount 100000000.
The private key for the coin corresponds to the same address that is used for script in TransactionOutput.
New 40 unspent outs with amount 1 QTUM you can see there https://pastebin.com/ar3nt88g (to see the whole code, please click raw).
Previous unspents vec was received using rpc_client.list_unspent(). Actual test code use coin.get_mature_unspent_ordered_list() to get vector of mature unspents. In new log https://pastebin.com/Airux7jv there are some new unspents due to couple iterations of test code, but we still can see outpoints with old hashes (from https://pastebin.com/ar3nt88g), so we can be sure, that program access the same coin address.

[r2r] split qtum utxo

---

azure-pipelines-build-stage-job.yml

This way we can analyze deployment commit history easier (since it will include commits from other repositories as well)

add commit prefix for playground node

---

mm2src/mm2_main/src/mm2.rs

Solving issue password_policy: constraints for rpc_password #1326
32 max length constraint was removed.

[r2r] Fix rpc_password length constraints

---

mm2src/coins/qrc20/history.rs
mm2src/coins/utxo/bch_and_slp_tx_history.rs
mm2src/coins/utxo/utxo_common.rs
mm2src/mm2_bitcoin/rpc/src/v1/types/hash.rs

Fixes #1321 for UTXO coins by removing outdated transactions from transaction history

[r2r] Remove outdated transactions from transaction history

---

mm2src/coins/rpc_command/get_current_mtp.rs
mm2src/coins/rpc_command/mod.rs
mm2src/mm2_main/src/docker_tests.rs
mm2src/mm2_main/src/mm2_tests.rs
mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs

- Implemented new rpc method for getting current mtp of UTXOs coins
- Added unit test 
- fixes #1338

[r2r] get_current_mtp rpc impl

---

mm2src/mm2_main/src/lp_ordermatch.rs

New enum variants should be added to the end to keep the rmp_serde serialization numeration.

[r2r] Fix P2P OrdermatchRequest backward compatibility.

---

mm2src/mm2_libp2p/src/peers_exchange.rs

* return random known peers with a maximum of DEFAULT_PEERS_NUM
* Do not respond to GetKnownPeers p2p msg if requested number is greater than DEFAULT_PEERS_NUM

Don't respond to GetKnownPeers p2p msg if the number of peers requested exceeds the default number (#1445)

---

mm2src/coins/coin_balance.rs
mm2src/coins/hd_wallet.rs
mm2src/coins/lp_coins.rs
mm2src/coins/rpc_command/get_new_address.rs
mm2src/coins/rpc_command/hd_account_balance_rpc_error.rs
mm2src/coins/utxo.rs
mm2src/coins/utxo/qtum.rs
mm2src/coins/utxo/utxo_common.rs
mm2src/coins/utxo/utxo_standard.rs
mm2src/coins/utxo/utxo_tests.rs
mm2src/common/custom_iter.rs
mm2src/crypto/src/bip44.rs

* Optimize `HDWalletCoinOps::derive_address` by adding HD addresses cache
* Add `HDWalletCoinOps::derive_addresses` that is optimized to derive multiple addresses
* Remove `TryUnzip` as it's not used more

[r2r] Fix and improve some aspects of Hardware wallet integration

---

Cargo.lock
azure-pipelines-build-stage-job.yml
mm2src/coins/lightning/ln_events.rs
mm2src/common/Cargo.toml
mm2src/common/custom_futures.rs
mm2src/common/executor/abortable_system/abortable_queue.rs
mm2src/common/executor/abortable_system/mod.rs
mm2src/common/executor/abortable_system/simple_map.rs
mm2src/common/executor/native_executor.rs
mm2src/common/executor/wasm_executor.rs
mm2src/mm2_test_helpers/src/for_tests.rs

* Remove `TimedMutexGuard` as it's not used anymore

[r2r] Use `futures_timer` crate and fix unstable tests

---

mm2src/coins/eth/v2_activation.rs
mm2src/coins/tendermint/tendermint_coin.rs

if no `gui_auth` was given, consider it as `false`

[r2r] default `gui-auth` param and increased used gas prediction

---

mm2src/mm2_main/src/mm2_lib/mm2_wasm_lib.rs

Signed-off-by: ozkanonur <work@onurozkan.dev>

remove unnecessary unsafe block

---

mm2src/coins/eth.rs
mm2src/coins/lightning.rs
mm2src/coins/lp_coins.rs
mm2src/coins/qrc20.rs
mm2src/coins/solana.rs
mm2src/coins/solana/spl.rs
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/coins/tendermint/tendermint_token.rs
mm2src/coins/test_coin.rs
mm2src/coins/utxo/bch.rs
mm2src/coins/utxo/qtum.rs
mm2src/coins/utxo/slp.rs
mm2src/coins/utxo/utxo_common.rs
mm2src/coins/utxo/utxo_standard.rs
mm2src/coins/z_coin.rs
mm2src/mm2_main/src/lp_swap/swap_watcher.rs

Removes the relevant parts where the watchers check if the taker payment is spent or refund at the beginning of the `ValidateTakerPayment` state. The check was unnecessary and could cause the watchers to stop if the maker already spent the taker payment at that point.

[r2r] Swap watcher bugfix

---

mm2src/coins/solana/spl_tests.rs
mm2src/coins/tendermint/iris/htlc.rs
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/coins/tendermint/tendermint_token.rs

Also implemented validate_address.
Add dummy error return for others to avoid occasional panics.
#1432 
This is one more P0 required for the upcoming WebDEX release.

[r2r] Implement methods used in recover_funds_of_swap for Tendermint.

---

mm2src/common/common.rs
mm2src/common/executor/wasm_executor.rs
mm2src/common/number_type_casting.rs
mm2src/mm2_main/src/mm2_lib/mm2_wasm_lib.rs

I think we should replace all the possible overflow cases with this implementation. Should we cover that in this PR? @artemii235 
Atm it only covers [this line](https://github.com/KomodoPlatform/atomicDEX-API/blob/ee078e58e47b43762314fc2d89b030990d0fcc24/mm2src/common/executor/wasm_executor.rs#L88) because @sergeyboyko0791 specifically asked for it [here](https://github.com/KomodoPlatform/atomicDEX-API/pull/1515#issuecomment-1295103002).
Opened from: https://github.com/KomodoPlatform/atomicDEX-API/pull/1515#issuecomment-1295127521
Resolves: #1500

[r2r] safe number type casting

---

Cargo.lock
mm2src/coins/Cargo.toml
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/coins/tendermint/tendermint_native_rpc.rs

[r2r] Port tendermint HTTP RPC client to use webpki roots instead of native.

---

mm2src/mm2_main/src/lp_ordermatch.rs

Currently, only `BTC` and not `BTC-segwit` use `4x` locktime, this PR fixes this situation. https://github.com/KomodoPlatform/atomicDEX-API/blob/7909eb1301a42007f9a7dc6bfb782ba3fe176ec0/mm2src/mm2_main/src/lp_swap.rs#L559-L569
Note: This breaks backward compatibility, since locktimes are exchanged and validated in the negotiation messages. Old nodes will not be able to swap BTC segwit with new nodes after this update.

[r2r] Use orderbook ticker to calculate swap locktimes

---

mm2src/coins/eth/v2_activation.rs

With https://github.com/KomodoPlatform/atomicdex-gui-auth/commit/95bf760edee9cc5273c8aa113c3654430edf799f we are now counting rates for each config. On API side, because we were directly cloning web instances all the assets are rated as `ETH`. This PR fixes it.

[r2r] proper eth token ticker for gui auth service

---

Cargo.lock
Cargo.toml
azure-pipelines-android-job.yml
azure-pipelines-build-stage-job.yml
azure-pipelines-ios-job.yml
azure-pipelines-lint-stage-job.yml
mm2src/coins/Cargo.toml
mm2src/mm2_main/Cargo.toml
mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
mm2src/mm2_main/tests/docker_tests/swaps_confs_settings_sync_tests.rs
mm2src/mm2_main/tests/integration_tests_common/mod.rs
mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
mm2src/mm2_main/tests/mm2_tests/orderbook_sync_tests.rs

- Separate profile inherited from dev speeds up compilation significantly. We don't need optimizations for nightly builds anyway because they are intended for testing purposes.
- Renamed lib to "mm2lib"
- Disabled default features of cosmrs - wasn't using them.

[r2r] Rename lib and create separate CI build profile.

---

mm2src/coins/rpc_command/hd_account_balance_rpc_error.rs
mm2src/coins/rpc_command/init_create_account.rs
mm2src/coins/utxo/utxo_withdraw.rs
mm2src/mm2_main/src/lp_init/init_hw.rs
mm2src/mm2_main/src/lp_init/init_metamask.rs
mm2src/mm2_main/src/lp_native_dex.rs
mm2src/rpc_task/src/handle.rs
mm2src/rpc_task/src/lib.rs
mm2src/rpc_task/src/manager.rs

The issue was:
1. `cancel_init_trezor`:
https://github.com/KomodoPlatform/atomicDEX-API/blob/6c90c28a29723dad6c48296bed3093686188eeb2/mm2src/mm2_main/src/lp_init/init_hw.rs#L209
2. `RpcTaskManager::cancel_task`:
https://github.com/KomodoPlatform/atomicDEX-API/blob/6c90c28a29723dad6c48296bed3093686188eeb2/mm2src/rpc_task/src/manager.rs#L111-L112
3. A corresponding item is removed from the `RpcTaskManager::tasks`:
https://github.com/KomodoPlatform/atomicDEX-API/blob/6c90c28a29723dad6c48296bed3093686188eeb2/mm2src/rpc_task/src/manager.rs#L21-L22
4. If the task is in `Awaiting` status, `abort_handle` **AND** `action_sender` are dropped
https://github.com/KomodoPlatform/atomicDEX-API/blob/6c90c28a29723dad6c48296bed3093686188eeb2/mm2src/rpc_task/src/manager.rs#L269-L274
5. I don't know why, but …

[r2r] Fix `task::*::cancel` if the RPC task is an awaiting status

---

mm2src/coins/lightning.rs
mm2src/coins/lightning/ln_conf.rs
mm2src/coins/lightning/ln_platform.rs
mm2src/coins/lp_coins.rs
mm2src/coins/utxo.rs
mm2src/coins/utxo/utxo_builder/utxo_conf_builder.rs
mm2src/coins/utxo/utxo_common_tests.rs
mm2src/coins_activation/src/l2/init_l2_error.rs
mm2src/coins_activation/src/lightning_activation.rs
mm2src/mm2_main/tests/mm2_tests/lightning_tests.rs

Since blocktimes in config will be in seconds after this PR https://github.com/KomodoPlatform/coins/pull/573 is merged, lightning can now use the platform coin blocktime for estimating the number of blocks swap payments are locked for.

[r2r] use avg_blocktime from platform/utxo coin for l2/lightning

---

mm2src/coins/lp_coins.rs
mm2src/coins/utxo.rs
mm2src/coins/utxo/rpc_clients.rs
mm2src/coins/utxo/utxo_builder/utxo_coin_builder.rs
mm2src/coins/utxo/utxo_tests.rs
mm2src/coins/utxo/utxo_wasm_tests.rs

#1613 
- Reset negotiated protocol version on disconnection.
- Do not use a connection for multi request if version negotiation is required, but it's not finished yet.
- Also fix `utxo_wasm_tests`.

[r2r] Fix server version negotiation race condition in Electrum client.

---

mm2src/coins/utxo_signer/src/with_trezor.rs
mm2src/mm2_bin_lib/src/lib.rs
mm2src/mm2_bin_lib/src/mm2_native_lib.rs
mm2src/mm2_bin_lib/src/mm2_wasm_lib.rs
mm2src/trezor/src/utxo/prev_tx.rs
mm2src/trezor/src/utxo/unsigned_tx.rs
wasm_build/index.html
wasm_build/script.js

* Set `expiry` for Zcash-based transactions. This fixes https://github.com/KomodoPlatform/atomicDEX-API/issues/1626

[r2r] Fix KMD withdraw with Trezor, add `mm2_stop` WASM FFI

---

mm2src/mm2_main/src/lp_swap/maker_swap.rs
mm2src/mm2_main/src/lp_swap/taker_swap.rs

[r2r] hotfix: add payment instructions success events to is_success check

---

mm2src/coins/tendermint/tendermint_coin.rs

Previous implementation was only checking timeout error, with this change we also check the healthcheck result. And print friendly debug messages.
Also increased timeout to 5 seconds from 3.

[r2r] improve rpc client rotation of tendermint

---

dev-logs/2023-feb/fixes/fix_swap_time_difference_err_message
mm2src/mm2_main/src/lp_swap/maker_swap.rs
mm2src/mm2_main/src/lp_swap/taker_swap.rs

https://github.com/KomodoPlatform/atomicDEX-API/issues/1115#issuecomment-1443738940

[r2r] Better error message for failing swaps due to a time difference between maker and taker

---

mm2src/mm2_main/src/lp_ordermatch.rs

This PR addresses two issues caused by trusting peers to report a valid timestamp for `PubkeyKeepAlive` network messages. 
First, this can cause an integer overflow during this operation: 
https://github.com/KomodoPlatform/atomicDEX-API/blob/4c66f02ea78bd097c5313bcec938229346073099/mm2src/mm2_main/src/lp_ordermatch.rs#L2986
Second, it prevents a malicious node from setting a timestamp very far into the future. A timestamp set very far into the future would result in the orders staying in a node's orderbook even after the peer that broadcasted it has gone offline.
What this does is ignore the `timestamp` value sent from the peer and instead set it to the current time at which the message was received.

Bugfix pubkey keepalive overflow and "forever orders"

---

.github/workflows/virustotal_scan.yml

Closes https://github.com/KomodoPlatform/atomicDEX-API/issues/790
I've added my VirusTotal API key to github secrets for this repo.
Tested workflow in fork at https://github.com/smk762/atomicDEX-API/actions
Example results at https://github.com/smk762/atomicDEX-API/releases/tag/test
Current triggers will initiate workflow whenever a release is created, edited, prereleased or published. In testing, it was found that the VirusTotal results will append to the release body, which will result in duplicated VirusTotal results section if prior results not deleted. 
We can limit the triggers, or just make sure to remove old results from the release body text when edits are made (e.g. file uploads, adding changelog etc).

Add workflow for VirusTotal results

---

deny.toml
mm2src/coins/tendermint/rpc/tendermint_wasm_rpc.rs
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/mm2_main/tests/mm2_tests/tendermint_tests.rs

We have failing tests due to the used cosmos testnet node, tests are ignored for now until we find another working node or get this node to work again.

[r2r] update testnet node of atom

---

mm2src/mm2_test_helpers/src/for_tests.rs

Test are passing locally except for `test qrc20::qrc20_tests::test_wait_for_confirmations_excepted ... FAILED` which is unrelated to these changes.

[r2r] Update pirate & zombie domains for tests

---

mm2src/coins/eth.rs
mm2src/coins/eth/eth_tests.rs
mm2src/coins/eth/eth_wasm_tests.rs
mm2src/coins/lp_coins.rs
mm2src/mm2_main/src/lp_swap/maker_swap.rs
mm2src/mm2_main/src/lp_swap/taker_swap.rs
mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs

[r2r] wait for EVM approval transaction confirmation

---

CHANGELOG.md
Cargo.lock
mm2src/common/Cargo.toml
mm2src/mm2_core/Cargo.toml
mm2src/mm2_io/Cargo.toml
mm2src/mm2_net/Cargo.toml
mm2src/mm2_rpc/Cargo.toml
mm2src/mm2_test_helpers/Cargo.toml
mm2src/mm2_test_helpers/src/for_tests.rs

the purpose of this PR is to get rid of almost unused `crossterm` dependency (it used only for colored log files output in tests) and couple of other "old" unneeded dependencies in tree, such as `crossterm_winapi`, `mio 0.7.13`, `miow`, `ntapi`, `signal-hook`, `signal-hook-mio`.

get rid of crossterm and crates dependent on it

---

CHANGELOG.md
mm2src/coins/eth.rs

fixes #1630. For more info. https://github.com/KomodoPlatform/atomicDEX-API/issues/1630#issuecomment-1401736168

call eth_getTransactionByHash in wait_for_confirmations to avoid race condition

---

CHANGELOG.md
mm2src/mm2_main/src/lp_swap.rs
mm2src/mm2_main/src/lp_swap/maker_swap.rs
mm2src/mm2_main/src/lp_swap/taker_swap.rs

[r2r] save pubkeys with prefix

---

.cargo/config
.github/workflows/dev-build.yml
.github/workflows/fmt-and-lint.yml
.github/workflows/release-build.yml
.github/workflows/test.yml
.github/workflows/virustotal_scan.yml
CHANGELOG.md

Using `ubuntu-latest` builds mm2 with gcc 12, which breaks compatibility with older versions. We must used a version that is not too old/recent(which this pr provides already) to provide wide support.
Resolves #1732

build linux x86-64 with reasonable glibc

---

.github/workflows/dev-build.yml
.github/workflows/fmt-and-lint.yml
.github/workflows/test.yml
CHANGELOG.md

- Skip certain steps for forked repositories (e.g [auth required ones](https://github.com/KomodoPlatform/atomicDEX-API/actions/runs/4514462628/jobs/7950614166#step:8:20))
- Do not run fmt/lint and test steps twice on dev-to-main PRs
- Start pipelines with a commit push right away without requiring PR opening to main or dev

improve CI/CD workflows

---

CHANGELOG.md
mm2src/coins/eth.rs
mm2src/coins/eth/eth_tests.rs
mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs

fixes https://github.com/KomodoPlatform/atomicDEX-API/pull/1724#issuecomment-1477710793, https://github.com/KomodoPlatform/atomicDEX-API/pull/1724#issuecomment-1477896138
Note: This fix might not work for load balanced nodes since we don't have a way to know which node behind the load balancer returned the latest nonce and the transaction might be sent to another node.

avoid waiting for all EVM nodes to sync the latest nonce

---

CHANGELOG.md
mm2src/coins/eth.rs
mm2src/coins/eth/eth_tests.rs
mm2src/coins/lightning.rs
mm2src/coins/lp_coins.rs
mm2src/coins/qrc20.rs
mm2src/coins/qrc20/qrc20_tests.rs
mm2src/coins/solana.rs
mm2src/coins/solana/spl.rs
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/coins/tendermint/tendermint_token.rs
mm2src/coins/test_coin.rs
mm2src/coins/utxo/bch.rs
mm2src/coins/utxo/qtum.rs
mm2src/coins/utxo/slp.rs
mm2src/coins/utxo/utxo_standard.rs
mm2src/coins/z_coin.rs
mm2src/mm2_main/src/lp_ordermatch.rs
mm2src/mm2_main/src/lp_swap/maker_swap.rs
mm2src/mm2_main/src/lp_swap/taker_swap.rs

`send_amount: BigDecimal` parameter was initially added for calculating receiver trade fee in cosmos swaps.
As it's been explained with the comments here:
https://github.com/KomodoPlatform/atomicDEX-API/blob/547a30a79b16da38769411772d837548922ee529/mm2src/coins/tendermint/tendermint_coin.rs#L1994-L1997
We are trying to simulate create HTLC transactions with the received amount, which causes tx errors if the sender sends more amount than what cosmos address has.
Because htlc amount doesn't increase the gas fee, I decided to remove that send amount parameter and use the minimum tx amount instead.
ref txs with different amounts and close gas fees:
- https://irishub.iobscan.io/#/txs/7B86592AD12C66AF86E42AC4BAB2D2C6A566495BC3914A7F75ABE3531C2B7C81
- …

fix `get_receiver_trade_fee` for cosmos

---

CHANGELOG.md
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/common/common.rs
mm2src/mm2_main/src/lp_ordermatch.rs
mm2src/mm2_main/src/lp_swap/maker_swap.rs
mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs

use OS generated secrets in `maker_swap` and `tendermint_coin::get_sender_trade_fee_for_denom` to achieve cryptographically secure randomness

use OS generated secrets

---

CHANGELOG.md
mm2src/coins/eth.rs
mm2src/coins/solana.rs
mm2src/coins/solana/spl.rs
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/coins/tendermint/tendermint_tx_history_v2.rs
mm2src/coins/utxo/utxo_tx_history_v2.rs
mm2src/coins_activation/src/bch_with_tokens_activation.rs
mm2src/coins_activation/src/eth_with_token_activation.rs
mm2src/coins_activation/src/platform_coin_with_tokens.rs
mm2src/coins_activation/src/prelude.rs
mm2src/coins_activation/src/solana_with_tokens_activation.rs
mm2src/coins_activation/src/tendermint_with_assets_activation.rs
mm2src/mm2_main/tests/docker_tests/slp_tests.rs
mm2src/mm2_main/tests/docker_tests/solana_tests.rs
mm2src/mm2_main/tests/mm2_tests/bch_and_slp_tests.rs
mm2src/mm2_main/tests/mm2_tests/eth_tests.rs
mm2src/mm2_main/tests/mm2_tests/tendermint_ibc_asset_tests.rs
mm2src/mm2_main/tests/mm2_tests/tendermint_tests.rs
mm2src/mm2_test_helpers/src/for_tests.rs
mm2src/mm2_test_helpers/src/structs.rs

fixes #1748
- This PR introduces several enhancements to the `enable_bch_with_tokens`, `enable_eth_with_tokens`, and `enable_tendermint_with_assets` requests.
- Firstly, token balance requests are now performed concurrently, which is expected to resolve any timeout issues that were occurring in GUIs if a shorter timeout is selected.
- Additionally, a new parameter called `get_balances` has been added to these requests. When set to `false`, balances and addresses are not requested or returned in the response. This option can be useful for users who prefer to poll `my_balance` for balances after activation, as it can speed up coin activations.
- Please note that the default value of `get_balances` is `true`, meaning that if this parameter is not set, the previous behavior will be …

Enhance enable with tokens methods

---

CHANGELOG.md
mm2src/coins/Cargo.toml
mm2src/coins/eth.rs
mm2src/coins/lp_coins.rs
mm2src/coins/nft.rs
mm2src/coins/nft/nft_errors.rs
mm2src/coins/nft/nft_structs.rs
mm2src/mm2_main/Cargo.toml
mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs

- url for proxy service was added in requests
- `possible_spam` field was added in `Nft` and `NftTransferHistory` structures
- make nft feature default
request examples
get_nft_list
```
{
"userpass": "'$USERPASS'",
"method": "get_nft_list",
"mmrpc": "2.0",
"params": {
"chains": [
"BSC",
"POLYGON"
],
"url": "https://moralis-proxy.komodo.earth"
}
}
```
get_nft_transfers
```
{
"userpass": "'$USERPASS'",
"method": "get_nft_transfers",
"mmrpc": "2.0",
"params": {
"chains": [
"POLYGON"
],
"url": "https://moralis-proxy.komodo.earth"
}
}
```
get_nft_metadata
```
{
"userpass": "'$USERPASS'",
"method": "get_nft_metadata",
"mmrpc": "2.0",
"params": {
"token_address": "0x5c7d6712dfaf0cb079d48981781c8705e8417ca0",
"token_id": "0",
"chain": "BSC",
"url": "https://moralis-proxy.komodo.earth"
}
}
``` …

Add proxy support

---

mm2src/mm2_test_helpers/src/for_tests.rs

Revert `BCHD_TESTNET_URLS` to the old one that was used since the certificate issue related to it is resolved.
According to this comment https://github.com/KomodoPlatform/atomicDEX-API/pull/1094#discussion_r723984586, I can't rely on multiple BCHDs to use only the one that is working similar to how it's done for other coins.

Revert BCHD testnet url to the previous url in unit tests

---

mm2src/mm2_main/src/lp_swap/taker_swap.rs

In the ETH/ERC20/UTXO swaps with watcher rewards PR https://github.com/KomodoPlatform/atomicDEX-API/pull/1750 , the coin used for `maker_payment_instructions` was changed from `maker_coin` to `taker_coin`
https://github.com/KomodoPlatform/atomicDEX-API/blob/a1fc8f7c92819f68c0dcdf7b1c650d86cdf945ad/mm2src/mm2_main/src/lp_swap/taker_swap.rs#L946-L956
This caused lightning swaps to fail. It wasn't catched by CI since lightning swaps unit tests are ignored because the `tBTC` addresses are required to be refilled periodically by coins which makes the test unstable.
https://github.com/KomodoPlatform/atomicDEX-API/blob/a1fc8f7c92819f68c0dcdf7b1c650d86cdf945ad/mm2src/mm2_main/tests/mm2_tests/lightning_tests.rs#L685-L689
This problem was also missed in the PR review.
I try to fix this issue in …

Hotfix: lightning swaps maker payment instructions

---

.github/workflows/dev-build.yml
.github/workflows/release-build.yml
.github/workflows/test.yml
Cargo.lock
mm2src/coins/Cargo.toml
mm2src/coins/eth.rs
mm2src/coins/nft.rs
mm2src/coins/nft/nft_structs.rs
mm2src/coins/nft/nft_tests.rs
mm2src/coins/utxo/utxo_builder/utxo_arc_builder.rs
mm2src/common/common.rs

Fixes https://github.com/KomodoPlatform/atomicDEX-API/pull/1804#pullrequestreview-1427165095, https://github.com/KomodoPlatform/atomicDEX-API/pull/1804#pullrequestreview-1428385468

Minor fixes for upcoming v1.0.4-beta release

---

CHANGELOG.md
Cargo.lock
mm2src/coins/Cargo.toml
mm2src/coins/lp_price.rs
mm2src/common/Cargo.toml
mm2src/common/time_cache.rs
mm2src/mm2_main/Cargo.toml
mm2src/mm2_main/src/lp_network.rs
mm2src/mm2_main/src/lp_ordermatch/order_requests_tracker.rs
mm2src/mm2_metrics/Cargo.toml
mm2src/mm2_metrics/src/mm_metrics.rs

This change excludes the deprecated dependency `wasm-timer` from mm2 tree. Right now, it's only used in the `p2p` stack from `libp2p` which will be removed from there as well with the https://github.com/KomodoPlatform/atomicDEX-API/issues/1756

exclude `wasm-timer` deprecated dependency

---

Cargo.lock
mm2src/coins/Cargo.toml
mm2src/common/Cargo.toml
mm2src/common/shared_ref_counter/Cargo.toml
mm2src/db_common/Cargo.toml
mm2src/gossipsub/Cargo.toml
mm2src/hw_common/Cargo.toml
mm2src/ledger/Cargo.toml
mm2src/mm2_bin_lib/Cargo.toml
mm2src/mm2_bitcoin/rpc/Cargo.toml
mm2src/mm2_bitcoin/script/Cargo.toml
mm2src/mm2_db/Cargo.toml
mm2src/mm2_libp2p/Cargo.toml
mm2src/mm2_main/Cargo.toml
mm2src/mm2_metamask/Cargo.toml
mm2src/mm2_net/Cargo.toml
mm2src/trezor/Cargo.toml

Bumps few dependencies to more recent versions to resolve version conflicts for using latest libp2p upstream.

upgrade `wasm-bindgen`, `getrandom` and `log`

---

mm2src/coins/utxo.rs
mm2src/coins/utxo/utxo_tests.rs

KMD interest calculation is adjusted to reduce AUR (Active User Rewards) from 5% to 0.01% starting from KMD block height `3484958` (Fri Jun 30 2023) according to [KIP-0001](https://github.com/KomodoPlatform/kips/blob/main/kip-0001.mediawiki)
fixes #1840

feat(kmd): reduce KMD AUR from 5% to 0.01% starting at nS7HardforkHeight

---

CHANGELOG.md
Cargo.lock
mm2src/mm2_bin_lib/Cargo.toml

This PR bumps the mm2 version to 1.0.5-beta and adds the corresponding changelog entries.

chore(release): bump mm2 version to 1.0.5-beta and add changelog entries

---

mm2src/coins/nft/nft_tests.rs

I removed len checks, because primarily we check that our nft Wrap structures and request methods work well

fix(nft): hot fix moralis tests

---

mm2src/coins/utxo.rs

fixes https://github.com/KomodoPlatform/atomicDEX-API/pull/1844#discussion_r1210433613

fix(kmd): remove conversions from/to float in AUR calculations

---

Cargo.lock
mm2src/coins/Cargo.toml
mm2src/mm2_libp2p/Cargo.toml
mm2src/mm2_main/Cargo.toml

dependency updates:
- `indexmap` `1.7.0` -> `1.9.3`
- `petgraph` `0.6.1` -> `0.6.3`
- `serde` `1.0.136` -> `1.0.164`
- `serde_derive` `1.0.136` -> `1.0.164`

fix(incompatible-dep): rollback rmp

---

mm2src/coins/eth.rs
mm2src/coins/eth/eth_tests.rs
mm2src/coins/eth/web3_transport/http_transport.rs
mm2src/mm2_main/src/lp_swap/maker_swap.rs
mm2src/mm2_main/src/lp_swap/taker_swap.rs
mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
mm2src/mm2_test_helpers/src/for_tests.rs

This PR:
- Moves the watchtower integration tests to the new ethereum testnet and removes the ignore attributes
- Adds a new test case for watcher rewards
- Fixes the unstable `send_and_refund_eth_payment`, `send_and_refund_erc20_payment`, `test_nonce_lock` and `test_withdraw_and_send` tests that were failing due to concurrency

feat(watchtower): move watchtower tests to new testnet

---

mm2src/coins/lp_price.rs

set `https://prices.komodo.earth:1313/api/v2/tickers` instead of `https://prices.komodo.live:1313/api/v2/tickers`

fix(endpoints): fix price endpoints in lp_price

---

Cargo.lock
mm2src/mm2_core/Cargo.toml
mm2src/mm2_core/src/mm_ctx.rs
mm2src/mm2_main/Cargo.toml
mm2src/mm2_main/src/rpc.rs
mm2src/mm2_net/Cargo.toml
mm2src/mm2_net/src/lib.rs
mm2src/mm2_net/src/native_tls/README.md
mm2src/mm2_net/src/native_tls/acceptor.rs
mm2src/mm2_net/src/native_tls/builder.rs
mm2src/mm2_net/src/native_tls/mod.rs

This PR adds a new mm2 config parameter `https`. When this parameter is set to true, mm2 automatically generates a self-signed certificate internally if no certificate and private key file is found in either the specified paths (`MM_CERT_PATH` and `MM_CERT_KEY_PATH`) as defined in the environment variables or if no `cert.pem` and `key.pem` files are found in the same directory as the compiled mm2 binary (similar to how coins file works).
For the self-signed certificate, the default SANs (Subject Alternative Names) used are `localhost` and `127.0.0.1`, these are set if `alt_names` is not specified in mm2 config. `alt_names` takes an array of strings specifying the desired SANs.
After certificates are loaded, the mm2 service/server is then executed in HTTPS mode, enabling secure …

feat(rpc): add https support

---

mm2src/mm2_main/src/mm2.rs

fixes https://github.com/KomodoPlatform/adex_bugtracking/issues/50

fix(logs): remove config string from deserialization error log

---

.github/workflows/pr-lint.yml

Add label validation on PRs. The validation will only succeed if one of the(not together) following labels is used: `under review` or `in progress`.

ci(pr-validation): check PR labels

---

mm2src/adex_cli/src/adex_app.rs
mm2src/adex_cli/src/adex_config.rs
mm2src/adex_cli/src/adex_proc/adex_proc_impl.rs
mm2src/adex_cli/src/adex_proc/command.rs
mm2src/adex_cli/src/adex_proc/response_handler.rs
mm2src/adex_cli/src/cli.rs
mm2src/adex_cli/src/logging.rs
mm2src/adex_cli/src/main.rs

adex-cli had a bug:
It was impossible to start if configuration does not exist, that has been fixed.

fix(adex-cli): fix bug start without config

---

mm2src/coins/lp_coins.rs
mm2src/coins/rpc_command/tendermint/ibc_withdraw.rs
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/coins/tendermint/tendermint_token.rs
mm2src/mm2_main/tests/mm2_tests/tendermint_tests.rs

IBC and standard withdrawals for Cosmos now allow users to specify the gas price and gas limit for each transaction. You can do this by including the following information in the RPC payloads:
```json
"fee": {
"type": "CosmosGas",
"gas_limit": 125000,
"gas_price": 0.25
}
```
e.g. payload in the integration test:
https://github.com/KomodoPlatform/atomicDEX-API/blob/af74b50b2714cf77c576e4a85c858e4b2a36191b/mm2src/mm2_main/tests/mm2_tests/tendermint_tests.rs#L162-L171
Determining the gas price to be used:
1- From the RPC payload.
2- From the coins configuration.
3- A default value of `0.25`, which is currently hardcoded in the source code.
Higher prior always overrides the others.
Resolves #1847
cc @yurii-khi @tonymorony

feat(cosmos): dynamic gas price and gas limit

---

.github/workflows/adex-cli.yml
.github/workflows/test.yml

test(new-flag): run all tests ignoring the failed ones

---

mm2src/coins/eth.rs
mm2src/coins/lp_coins.rs
mm2src/coins/nft.rs
mm2src/coins/nft/nft_errors.rs
mm2src/coins/nft/nft_structs.rs
mm2src/coins/nft/nft_tests.rs
mm2src/coins/nft/storage/db_test_helpers.rs
mm2src/coins/nft/storage/mod.rs
mm2src/coins/nft/storage/sql_storage.rs
mm2src/coins/nft/storage/wasm/wasm_storage.rs
mm2src/mm2_core/src/mm_ctx.rs

solves notes in #1871
solves notes in #1871
solves mm2 error from #1909 
fixes runtime cursor error in wasm `Uncaught Error: closure invoked recursively or after being dropped` related to `IdbCursor::continue_` and `IdbIndex::open_cursor_with_range_and_direction`
also error from #1909

fix(nft): fix notes for 1.0.6-beta

---

mm2src/coins/utxo/bch.rs
mm2src/coins/utxo/utxo_common.rs
mm2src/coins/utxo/utxo_common/utxo_tx_history_v2_common.rs
mm2src/mm2_main/src/lp_swap/taker_swap.rs

Partially fixes #1906
This PR addresses index out of bounds errors in the `tx_details_by_hash` functions. The changes replace direct array access with safer methods, avoiding potential panics due to out-of-range indices. In addition, error handling around the function was improved to log and skip transactions in case of errors.
Please note that while this PR doesn't fully resolve the issue outlined in https://github.com/KomodoPlatform/komodo-wallet-desktop/issues/2317, as the transactions causing panics during history fetching will be skipped instead. The PR will facilitate the pinpointing of the actual problem by logging the transactions that cause these issues.

fix(utxo): avoid index out of bounds panics in tx_details_by_hash

---

mm2src/coins/utxo.rs

this is a fix for the Reddcoin withdrawal issue.
electrum was reporting that it could not parse transaction
On investigating, the issue was a missing n_time field in the generated transaction
The fix now correctly considers when n_time is required, and the rawtransaction can be broadcast

fix(posv): fix missing n_time in posv transactions

---

mm2src/mm2_main/tests/mm2_tests/tendermint_tests.rs

Fixes `mm2_tests::tendermint_tests::test_tendermint_ibc_withdraw` test which fails as:
```log
thread 'mm2_tests::tendermint_tests::test_tendermint_ibc_withdraw' panicked at 'assertion failed: `(left == right)`
left: `500`,
right: `200`: 'ibc_withdraw' failed: {"mmrpc":"2.0","error":"Transport error: Could not read gas_info. Error code: 6 Message: rpc error: code = Unknown desc = failed to execute message; message index: 0: cannot send packet using client (07-tendermint-120) with status Expired: client is not active [cosmos/ibc-go/v5@v5.2.0/modules/core/04-channel/keeper/packet.go:74] With gas wanted: '18446744073709551615' and gas used: '71366' : unknown request","error_path":"tendermint_token.tendermint_coin","error_trace":"tendermint_token:180] …
```

fix(ibc-test): use latest relayer channel for tendermint test

---

mm2src/coins/lp_price.rs
mm2src/mm2_main/src/lp_ordermatch/simple_market_maker.rs

new: https://prices.komodo.earth/api/v2/tickers
old: https://prices.komodo.earth:1313/api/v2/tickers

fix(endpoints): update prices url

---

mm2src/coins/nft.rs
mm2src/coins/nft/nft_structs.rs
mm2src/coins/nft/nft_tests.rs
mm2src/coins/nft/storage/db_test_helpers.rs
mm2src/coins/nft/storage/mod.rs
mm2src/coins/nft/storage/sql_storage.rs
mm2src/coins/nft/storage/wasm/nft_idb.rs
mm2src/coins/nft/storage/wasm/wasm_storage.rs

fixes https://github.com/KomodoPlatform/komodo-wallet/issues/1239#issuecomment-1658128185
related comment https://github.com/KomodoPlatform/komodo-wallet/issues/1239#issuecomment-1658670188
- This PR fixes transactions that transfer multiple NFT tokens in db. These transactions cause errors when adding due to the db constraint on tx hash uniqueness. To solve this, the PR uses `log_index` as part of the transfers history table primary key.
- `nft_tx_history` table is now called `nft_transfer_history` and `tx`/`txs` are renamed to `transfer`/`transfers` throughout the NFT code since what's added/retrieved from DB is NFT transfers not transactions (Multiple NFT transfers can be in one transaction). By renaming the table, there are no need for db migrations due to the addition of `log_index` …

fix(nft): add log_index to history table and use in PK

---

mm2src/adex_cli/src/rpc_data.rs

Activation scheme was changed and that is why the related data types had to be fit to it
Related changes in [kmd_ntx_stats_docker](https://github.com/smk762/kmd_ntx_stats_docker/commit/ff6429452d8e9bc496f591c0c25286d667baf1b9)

fix(cli): use the updated activation scheme

---

mm2src/coins/utxo/bchd_grpc.rs
mm2src/coins/utxo/slp.rs

This PR ignores tests that use BCHD only. For other failing tests:
- Failing docker_tests are fixed and passing in this PR https://github.com/KomodoPlatform/komodo-defi-framework/pull/1908
- I will look into utxo_lock failing test and wasm failures later

fix(tests): ignore failing tests due to BCHD

---

docs/DEV_ENVIRONMENT.md
mm2src/coins/eth/eth_tests.rs
mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
mm2src/mm2_main/tests/mm2_tests/best_orders_tests.rs
mm2src/mm2_main/tests/mm2_tests/eth_tests.rs
mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
mm2src/mm2_test_helpers/src/for_tests.rs

Fix regex to parse passphrase from .env file if newline char added

fix(tests): fix regex parsing passphrase from .env file

---

mm2src/coins/utxo/utxo_tests.rs
mm2src/mm2_test_helpers/src/electrums.rs
mm2src/mm2_test_helpers/src/for_tests.rs

This PR fixes failing wasm tests and `test_utxo_lock` by making these tests use the `DOC`/`MARTY` electrums. I will be working on another PR that moves all `RICK`/`MORTY` tests to the new testnets and should rename the coins too (although it's not required to rename them).

fix(tests): fix failing tests due to RICK/MORTY

---

mm2src/coins/eth.rs
mm2src/coins/qrc20.rs
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/coins/tendermint/tendermint_token.rs
mm2src/mm2_main/src/lp_ordermatch.rs
mm2src/mm2_main/src/lp_swap.rs
mm2src/mm2_main/src/lp_swap/taker_swap.rs
mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs

fixes https://github.com/KomodoPlatform/komodo-defi-framework/issues/884

fix(fee): remove fixed 0.0001 min threshold for TakerFee

---

Cargo.lock
mm2src/mm2_main/src/ordermatch_tests.rs
mm2src/mm2_net/Cargo.toml
mm2src/mm2_net/src/p2p.rs

For some reason, mocktopus dependency can not mock the p2p context after the p2p stack upgrade. 
This PR fixes that(by not doing it magically).

fix(tests): p2p ctx mocking issue

---

mm2src/coins/utxo/utxo_tests.rs
mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs

- Minimum price threshold changed here https://github.com/KomodoPlatform/komodo-defi-framework/pull/1971
- Recommendation for more tbch electrums https://github.com/KomodoPlatform/komodo-defi-framework/pull/1968#issuecomment-1729670967

fix(tests): fix unstable tbch tests and failing price threshold test

---

.docker/Dockerfile
.docker/Dockerfile.ci-container
.docker/Dockerfile.ubuntu.ci
README.md
docs/RASPBERRY_PI4_CROSS.md

This PR aims:
- to remove unnecessary informations from the documentations.
- to avoid manual toolchain installations in container images (rustup can handle this already with `rust-toolchain.toml`).
- to add new guideline about compiling source from container under `Building from source` topic.

chore(containers and docs): update docs and container images

---

mm2src/coins/eth.rs
mm2src/coins/eth/eth_tests.rs
mm2src/coins/lightning.rs
mm2src/coins/lp_coins.rs
mm2src/coins/qrc20.rs
mm2src/coins/qrc20/qrc20_tests.rs
mm2src/coins/solana.rs
mm2src/coins/solana/spl.rs
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/coins/tendermint/tendermint_token.rs
mm2src/coins/test_coin.rs
mm2src/coins/utxo/bch.rs
mm2src/coins/utxo/qtum.rs
mm2src/coins/utxo/slp.rs
mm2src/coins/utxo/utxo_common.rs
mm2src/coins/utxo/utxo_standard.rs
mm2src/coins/utxo/utxo_tests.rs
mm2src/coins/z_coin.rs
mm2src/coins/z_coin/z_coin_native_tests.rs
mm2src/mm2_bitcoin/script/src/builder.rs
mm2src/mm2_main/src/lp_ordermatch.rs
mm2src/mm2_main/src/lp_swap.rs
mm2src/mm2_main/src/lp_swap/maker_swap.rs
mm2src/mm2_main/src/lp_swap/taker_swap.rs
mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs

For KMD, taker fee payment algorithm is updated by burning up to 25% of the dex fee amount.
Helps with: https://github.com/KomodoPlatform/komodo-defi-framework/issues/2010

feat(UTXO swaps): kmd burn plan impl

---

Cargo.lock
mm2src/coins/eth.rs
mm2src/coins/my_tx_history_v2.rs
mm2src/coins/nft.rs
mm2src/coins/nft/nft_errors.rs
mm2src/coins/nft/nft_structs.rs
mm2src/coins/nft/nft_tests.rs
mm2src/coins/nft/storage/db_test_helpers.rs
mm2src/coins/nft/storage/mod.rs
mm2src/coins/nft/storage/sql_storage.rs
mm2src/coins/nft/storage/wasm/mod.rs
mm2src/coins/nft/storage/wasm/wasm_storage.rs
mm2src/db_common/Cargo.toml
mm2src/db_common/src/async_conn_tests.rs
mm2src/db_common/src/async_sql_conn.rs
mm2src/db_common/src/lib.rs
mm2src/mm2_core/src/mm_ctx.rs
mm2src/mm2_main/src/lp_native_dex.rs
mm2src/mm2_main/src/rpc/lp_commands/lp_commands_legacy.rs
mm2src/mm2_test_helpers/src/for_tests.rs

continuation of this [PR](https://github.com/KomodoPlatform/komodo-defi-framework/pull/1959).
solves [comment](https://github.com/KomodoPlatform/komodo-defi-framework/pull/1959#issuecomment-1718782560) and [issue](https://github.com/KomodoPlatform/komodo-defi-framework/issues/1943).
- `nft_cache_db` was added in `NftCtx` for non wasm target.
- [ Changelog of Async sqlite wrapper gist](https://gist.github.com/laruh/6f7fc778d0c53d7f91fb70e27968bff6)
- `AsyncConnection` structure was created in  `mm2src/db_common/src/async_sql_conn.rs`. It can be used as async wrapper for sqlite connection.
- `async_sqlite_connection` field was added in `MmCtx`.
According to [this](https://github.com/ethereum/go-ethereum/issues/22653#issuecomment-817871794)  `transaction_receipt(hash)` can return `None` for …

feat(nft): move db lock, add tx fee and confirmations

---

mm2src/mm2_core/src/mm_ctx.rs

fix(config): accept a string for rpcport value

---

Cargo.lock
mm2src/mm2_p2p/Cargo.toml
mm2src/mm2_p2p/src/behaviours/peers_exchange.rs
mm2src/mm2_p2p/src/behaviours/request_response.rs

From https://github.com/KomodoPlatform/rust-libp2p/blob/port-from-old-impl/muxers/yamux/CHANGELOG.md
> yamux v0.13 enables auto-tuning for the Yamux stream receive window. While preserving small buffers on low-latency and/or low-bandwidth connections, this change allows for high-latency and/or high-bandwidth connections to exhaust the available bandwidth on a single stream. Have libp2p-yamux use yamux v0.13 (new version) by default and fall back to yamux v0.12 (old version) when setting any configuration options. Thus default users benefit from the increased performance, while power users with custom configurations maintain the old behavior. libp2p-yamux will switch over to yamux v0.13 entirely with the next breaking release. See https://github.com/libp2p/rust-libp2p/pull/4970. …

deps(network): sync with upstream yamux

---

mm2src/coins/lp_price.rs

The current urls sometimes become rate limited, especially when testing across a few instances of mm2 at the same time.
I've added an additional `PRICE_ENDPOINTS` url which is a cached copy of https://prices.komodian.info/api/v2/tickers, updated every minute. This should sever as a reliable fallback when rate limiting becomes an issue.

fix(price_endpoints): add cached url

---

mm2src/mm2_p2p/src/behaviours/atomicdex.rs
mm2src/mm2_p2p/src/lib.rs

This should be useful as not requiring to find the mm2 ports on the operating system.
cc @smk762

chore(network): write network information to stdout

---

mm2src/mm2_main/src/lp_ordermatch.rs
mm2src/mm2_main/src/lp_swap.rs
mm2src/mm2_p2p/src/lib.rs

fixes https://github.com/KomodoPlatform/komodo-defi-framework/pull/1968#discussion_r1428067679

fix(p2p): handle encode_and_sign errors

---

Cargo.lock
mm2src/coins/Cargo.toml
mm2src/coins/eth.rs
mm2src/coins/eth/eth_balance_events.rs
mm2src/coins/eth/v2_activation.rs
mm2src/coins/lp_coins.rs
mm2src/coins/tendermint/tendermint_balance_events.rs
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/coins/utxo/utxo_balance_events.rs
mm2src/coins_activation/src/eth_with_token_activation.rs
mm2src/coins_activation/src/platform_coin_with_tokens.rs
mm2src/mm2_event_stream/src/behaviour.rs

This PR aims to:
- Implement balance events for ETH.
- Implement error events.
Can be tested in a same way of https://github.com/KomodoPlatform/komodo-defi-framework/pull/1978 PR.

feat(ETH): balance event streaming for ETH

---

Cargo.lock
mm2src/adex_cli/Cargo.lock

See https://github.com/advisories/GHSA-8r5v-vm4m-4g25

deps(network): security bump for `h2`

---

mm2src/mm2_main/src/database.rs
mm2src/mm2_main/src/database/stats_swaps.rs

This PR aims to store the `gui` and `mm_version` data in the `stats_swaps` table.
Since `gui` and `mm_version` isn't communicated in swap messages, we only store *our* gui and version.
Seed nodes are able to store both maker and taker's gui and version since they get both.
fixes #2047

feat(stats_swaps): add gui version in status db

---

Cargo.lock
mm2src/mm2_main/src/lp_native_dex.rs
mm2src/mm2_p2p/src/behaviours/atomicdex.rs
mm2src/mm2_p2p/src/behaviours/mod.rs

feat(config): add `max_concurrent_connections` to mm2

---

mm2src/mm2_p2p/src/behaviours/atomicdex.rs
mm2src/mm2_p2p/src/behaviours/peers_exchange.rs
mm2src/mm2_p2p/src/behaviours/request_response.rs

Fixes #2073
cc @KomodoPlatform/qa

feat(network): improve efficiency of known peers handling

---

mm2src/mm2_event_stream/src/lib.rs
mm2src/mm2_net/Cargo.toml
mm2src/mm2_net/src/wasm_event_stream.rs

This PR allows any worker path to be used instead of hardcoded `worker.js` file. The worker path can be specified using `worker_path` in `event_stream_configuration`,  if not specified `worker.js` will be used as default. Example:
```json
"event_stream_configuration": {
"access_control_allow_origin": "*",
"active_events": {
"NETWORK": { "stream_interval_seconds": 1.5 }
},
"worker_path": "index.js" // This can be added in wasm only configuration
}

feat(event streaming): configurable worker path, use SharedWorker

---

mm2src/coins/eth/eth_rpc.rs

Previously, encountering an error on any type of request even if it was invalid would result in a `failed due to not being able to find a living RPC client` error. This is obviously not correct and this PR makes it to return correct errors.

fix(eth): error handling in RPCs

---

Cargo.lock
mm2src/coins/Cargo.toml

This requires this PR https://github.com/KomodoPlatform/librustzcash/pull/9 to be merged first

deps(zcoin): use librustzcash that uses the same `aes` version as mm2

---

Cargo.lock
mm2src/mm2_net/Cargo.toml
mm2src/mm2_net/src/wasm/wasm_ws.rs

This test kept failing because If you give a partial or incomplete URL to the WebSocket::new constructor, the browser tries to fix it by adding it to the current page's web address. 
For our test case, `Websocket::new("invalid address")` will return this URL `ws://127.0.0.1:52732/invalid%20address` as the webpage is being hosted on my pc using port `52732`.
https://github.com/KomodoPlatform/komodo-defi-framework/blob/f0b21dccacb846510e2eb8f2150b1fd02fffd9dd/mm2src/mm2_net/src/wasm/wasm_ws.rs#L782-L795

fix(wasm): websocket url validation

---

mm2src/coins/utxo/bch.rs
mm2src/mm2_bitcoin/chain/src/block_header.rs
mm2src/mm2_bitcoin/serialization/src/reader.rs

This PR fixes `BCH` block header deserialization by making it the same as `BTC`

fix(BCH): deserialize BCH header that uses KAWPOW version correctly

---

README.md

Each item of this block of documentation is incorrect. Our platform support is not limited to 64-bit architecture, we don't actually require 2GB of RAM (I strongly believe that we never have, at the very least for the past 2 years), and we don't need any root privileges.

docs(README): remove outdated information

---

mm2src/coins/tendermint/tendermint_token.rs

As makers may not have a balance in the coin they want to swap, we need to calculate `get_receiver_trade_fee` in platform coin.
Same goes for ETH assets: https://github.com/KomodoPlatform/komodo-defi-framework/blob/b0fd99e8406e67ea06435dd028991caa5f522b5c/mm2src/coins/eth.rs#L4892-L4895

fix(tendermint): fee calculation

---

mm2src/common/common.rs
mm2src/mm2_core/src/mm_ctx.rs
mm2src/mm2_main/src/mm2.rs

Consolidates all the runtime files together under `$HOME/.kdf` by default (so you don't have to set environment variables on the host). This should improve the user experience significantly as this is a standard practice followed by most of the programs on UNIX systems.

feat(app-dir): implement root application dir `.kdf`

---

mm2src/mm2_main/src/lp_swap/maker_swap.rs
mm2src/mm2_main/src/lp_swap/taker_restart.rs
mm2src/mm2_main/src/lp_swap/taker_swap.rs
mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs

Fix missed apply_event for events discovered while taker was offline, like the maker spent or watcher refunded the taker payment.
Closes this https://github.com/KomodoPlatform/komodo-defi-framework/issues/2111

fix(utxo-swap): apply events occurred while taker down

---

mm2src/coins/eth.rs

`sign_and_send_transaction_with_keypair` should use the address provided from the caller instead of having my_address inside it. Thanks @dimxy for finding this.

fix(eth): remove my_address from sign_and_send_transaction_with_keypair

---

mm2src/mm2_main/tests/mm2_tests/best_orders_tests.rs
mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
mm2src/mm2_main/tests/mm2_tests/orderbook_sync_tests.rs
mm2src/mm2_test_helpers/src/for_tests.rs

Testnet bitcoin currently has high fees which causes some tests to fail due to not enough balance. Since `test_withdraw_segwit` tests only withdraw and not sending, we can set a fixed fee to fix this test.

fix(tests): set txfee for some tbtc tests

---

mm2src/mm2_main/src/lp_ordermatch/my_orders_storage.rs
mm2src/mm2_main/src/lp_swap/saved_swap.rs

To avoid concurrent reading/writing enable .tmp file technic for swap and order files.
Closes #2117
See also this note: https://github.com/KomodoPlatform/komodo-defi-framework/issues/2117#issuecomment-2107793514 
Note: this fix should not create a problem for two mm2 instances running on the same node as both would use different directories for their data, derived from different listening IP-addresses.

fix(swap): use tmp file for swap and order files

---

mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs

Test test_taker_completes_swap_after_taker_payment_spent_while_offline sometimes fails, apparently due to too early taker stop, so it does not have time to send p2p message with taker payment data to the maker.
This fix improves the test log wait condition to ensure the p2p message is sent and only then taker stops.

fix(test): improve log wait condition to fix taker restart test

---

mm2src/coins/lightning/ln_sql.rs
mm2src/coins/lightning/ln_utils.rs
mm2src/db_common/src/sqlite.rs

Addresses bunch of potential database problems by improving the validation function.

fix(core): improve validation rules for table names

---

mm2src/coins/tendermint/tendermint_coin.rs
mm2src/coins/tendermint/tendermint_token.rs

Fixes a regression (check `mm2_tests::tendermint_tests::test_tendermint_withdraw_hd` test) which started with pubkey-only activation implementation.

fix(core): tendermint withdraws on hd accounts

---

mm2src/mm2_main/src/lp_swap/max_maker_vol_rpc.rs

`max_maker_vol` RPC is actively used by client applications and does not rely on swap operations. This change allows wallet-only mode assets to use `max_maker_vol` RPC.

fix(restrictions): remove wallet-only restriction from max_maker_vol

---

.docker/Dockerfile.dev-release
.docker/Dockerfile.release
.docker/Dockerfile.ubuntu.ci
.dockerignore
.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/dev-build.yml
.github/workflows/release-build.yml
.github/workflows/test.yml
.github/workflows/validate-mm2-version.yml
.gitignore
README.md
mm2src/mm2_bin_lib/Cargo.toml
mm2src/mm2_main/src/mm2.rs
scripts/mm2/client/client
scripts/mm2/client/client_debug
scripts/mm2/seed/run
scripts/mm2/seed/run_debug

This PR renames mm2 binaries and libs to kdf

chore(bin): rename mm2 binaries to kdf

---

.github/workflows/dev-build.yml
.github/workflows/release-build.yml

`github-action-scp` stopped working for all machines except windows for some reason, this PR switches to [easingthemes/ssh-deploy@v5.0.3](https://github.com/easingthemes/ssh-deploy/releases/tag/v5.0.3) for all builds uploads except windows ones. `ssh-deploy` uses rsync over ssh and brings some benefits such as using Node.js 20 in v5.0.3, data integrity of transferred files by using checksums and compressing file data during transfer among other things.

fix(ci-builds): use ssh-deploy action for all builds except windows

---

.docker/Dockerfile.ci-container
.github/actions/deps-install/action.yml
.github/workflows/dev-build.yml
.github/workflows/release-build.yml
scripts/ci/upload_artifact.py

ci(artifacts): upload build artifacts with in-tree script

---

.gitignore
mm2src/mm2_io/src/fs.rs
mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
mm2src/mm2_main/tests/docker_tests_main.rs

This PR introduces containers runtime directories for dockerized tests to ensure files consistency with each run and prevent local file changes with each test execution:
- Added a function to recursively create and copy directories.
- Modified Atom and Nucleus docker nodes setup to utilize runtime directories.
- Added `.docker/container-runtime/` to .gitignore to avoid tracking temporary test data.
Thanks @onur-ozkan for the idea.

fix(docker-tests): implement containers runtime directories

---

mm2src/coins/tendermint/tendermint_balance_events.rs
mm2src/common/common.rs

Extends `common::http_uri_to_ws_address` helper to include address path.

fix(helpers): extend http to ws address conversion

---

.github/workflows/dev-build.yml
.github/workflows/release-build.yml

Add target for macOS on Apple Silicon. The GUI project has a new dependency that is incompatible with x86 architecture on macOS, breaking the current solution of building for x86 and running on Rosetta.

ci(artifact): add target for macos on apple silicon

---

mm2src/coins/tendermint/tendermint_coin.rs
mm2src/coins/tendermint/tendermint_token.rs
mm2src/mm2_main/tests/docker_tests/tendermint_tests.rs

This change makes kdf to resolve account sequence numbers locally without needing to perform RPC requests. In addition, avoids the use of incorrect sequence numbers that may come from cached responses.

feat(tendermint): implement better sequence resolving logic

---

mm2src/coins/eth.rs
mm2src/coins/eth/eth_tests.rs
mm2src/coins/eth/for_tests.rs
mm2src/coins/eth/nft_swap_v2/mod.rs
mm2src/coins/eth/v2_activation.rs

In PR #2051 there were added several gas limit constants to allocate gas price more precisely for different swap operations and for sending coin and tokens, instead of the old single capped value. However there are also erc20 tokens which are called over proxy contracts, which require more gas.
This PR:
- increases the default consts for erc20 ops (to the old value actually) to ensure proxied erc20 would have enough gas 
- adds gas_limit param to coins file to allow setting lower (or higher) gas limits for selected tokens
Fixes #2135
Sample of `gas_limit` (with all available limit values) in the coins file:
```
{
"coin": "ETH",
"gas_limit": {
"eth_send_coins": 21000,               -- Gas limit for sending coins 
"eth_send_erc20": 65000,              -- Gas limit for sending ERC20 tokens …
```

feat(ETH): add gas_limit coins param to override default values

---

.cargo/config.toml

This is to avoid the below warning when running commands such as `cargo +nightly fmt`
```bash
/atomicDEX-API/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
```

chore(cargo-config): migrate to `config.toml` to avoid warning

---

mm2src/coins/utxo_signer/src/with_key_pair.rs
mm2src/mm2_bitcoin/keys/src/keypair.rs
mm2src/mm2_bitcoin/keys/src/private.rs
mm2src/mm2_bitcoin/script/src/sign.rs

Attempts to fix https://github.com/KomodoPlatform/komodo-defi-framework/issues/2171

fix(zcoin): don't force low r signing to generate htlc pubkey for zcoin

---

mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
mm2src/mm2_main/tests/docker_tests/tendermint_tests.rs
mm2src/mm2_main/tests/docker_tests_main.rs

This will help me while reviewing other PRs. @onur-ozkan you can enable them again when you have time to fix the IBC node.

ci(docker-tests): ignore tendermint IBC tests for now

---

README.md

use `dev` branch for git badges

docs(README): update commit badges to use dev branch

---

.github/workflows/test.yml
mm2src/mm2_main/src/rpc.rs

@KomodoPlatform/qa **To Test:**
Already tested by @CharlVS
No docs needed for this PR.

fix(cors): allow OPTIONS request to KDF server

---

mm2src/coins/Cargo.toml

so that coins could be compiled (`cargo check`ed, `cargo test`ed) on its own
**To Test:**
Nothing, this internal KDF PR.

fix(coins): add p2p feature to mm2_net dependency

---

mm2src/mm2_bin_lib/Cargo.toml

Our WASM builds are fairly quicker than the other ones. We can afford couple extra minutes on that runner.

chore(WASM-builds): remove `wasm-opt` overriding

---

mm2src/mm2_core/src/mm_ctx.rs
mm2src/mm2_main/src/lp_native_dex.rs

KDF was creating the default all zeroes db dir on start which is not used, this PR fixes this.

fix(db): stop creating the all-zeroes dir on KDF start

---

mm2src/mm2_main/Cargo.toml
mm2src/mm2_main/src/rpc.rs

as discussed internally https://matrix.to/#/!yeLsKrHmWqEMEAILHs:matrix.org/$mAxamnv9Ga8rxAg24mXAUwRu9bKQArw2tB_aNaA177c?via=matrix.org, we need to test this doesn't break anything.

fix(native-rpc): remove escaped response body

---

clippy.toml
mm2src/coins/eth/eth_tests.rs
mm2src/coins/lightning/ln_platform.rs
mm2src/coins/qrc20/qrc20_tests.rs
mm2src/coins/solana/solana_tests.rs
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/coins/utxo/slp.rs
mm2src/coins/utxo/utxo_tests.rs
mm2src/coins/z_coin/z_coin_native_tests.rs
mm2src/common/common.rs
mm2src/mm2_err_handle/src/map_to_mm_fut.rs
mm2src/mm2_err_handle/src/mm_error.rs
mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
mm2src/mm2_main/tests/docker_tests/swap_proto_v2_tests.rs
mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs

Encountered an issue regarding a tokio tcp stream that breaks because it was spawned in a non-tokio runtime (in #1966).
These `.wait` methods used were using a different runtime - from `futures` - to run the future, but we could have instead did `block_on(fut.compat())` and run it on MM2's tokio runtime.
PRing this on its own to reduce the clutter in #1966 :)

chore(tests): don't use `.wait()` and use `block_on` instead

---

mm2src/mm2_core/src/lib.rs
mm2src/mm2_core/src/mm_ctx.rs
mm2src/mm2_io/src/fs.rs
mm2src/mm2_main/src/lp_wallet.rs
mm2src/mm2_main/src/lp_wallet/mnemonics_storage.rs
mm2src/mm2_main/src/lp_wallet/mnemonics_wasm_db.rs
mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
mm2src/mm2_main/src/wasm_tests.rs
mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
mm2src/mm2_test_helpers/src/for_tests.rs
mm2src/mm2_test_helpers/src/structs.rs
mm2src/proxy_signature/src/lib.rs

This PR introduces the `get_wallet_names` RPC method, which allows clients to retrieve information about all wallet names and the currently active one.
- **`get_wallet_names` Method**: Retrieves all wallet names and the active wallet's name if there is an active one. If there is no active wallet (no-login mode), it returns null for the active wallet's name.
```json
{
"userpass": "{{userpass}}",
"mmrpc": "2.0",
"method": "get_wallet_names"
}
```
```json
{
"mmrpc": "2.0",
"result": {
"wallet_names": ["Test 1", "Test 2"],
"activated_wallet": null
},
"id": null
}
```
```json
{
"mmrpc": "2.0",
"result": {
"wallet_names": ["Test 1", "Test 2"],
"activated_wallet": "Test 1"
},
"id": null
}
```
**To Test:** @KomodoPlatform/qa
Example request and responses are above, I already tested this and …

feat(wallets): add `get_wallet_names` rpc

---

mm2src/mm2_core/src/mm_ctx.rs

`db_root` function was duplicated due to it being created in 2 branches that were merged to dev. This PR fixes this.

fix(merge): remove duplicated `db_root` function

---

.github/actions/deps-install/action.yml
.github/actions/download-and-verify/action.yml
.github/workflows/test.yml

This PR updates GHA runners to use locked scripts rather than always using the latest one from the master branch. It also adds  a new GHA helper/plugin to easily download files and verify their checksums.
cc @Alrighttt

feat(CI): handle remote files in a safer way

---

mm2src/mm2_main/src/mm2.rs

sequel to https://github.com/KomodoPlatform/komodo-defi-framework/pull/2216

chore(cli): remove leftover subcommands from help message

---

mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
mm2src/mm2_main/tests/docker_tests/tendermint_tests.rs
mm2src/mm2_main/tests/docker_tests_main.rs

Fixes the weird "expired channel" bug and re-enables [ignored IBC tests](https://github.com/KomodoPlatform/komodo-defi-framework/pull/2185).
Blocker on https://github.com/KomodoPlatform/komodo-defi-framework/pull/2245.

feat(cosmos-offline-tests): prepare IBC channels inside the container 

---

mm2src/coins/eth.rs
mm2src/coins/lightning.rs
mm2src/coins/lp_coins.rs
mm2src/coins/qrc20.rs
mm2src/coins/siacoin.rs
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/coins/tendermint/tendermint_token.rs
mm2src/coins/test_coin.rs
mm2src/coins/utxo/bch.rs
mm2src/coins/utxo/qtum.rs
mm2src/coins/utxo/slp.rs
mm2src/coins/utxo/utxo_standard.rs
mm2src/coins/z_coin.rs
mm2src/coins/z_coin/z_coin_native_tests.rs
mm2src/mm2_main/src/lp_swap/maker_swap.rs
mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs

This is needed for SIA. Will convert all other SwapOps trait methods to async in another PR after this is merged.

refactor(SwapOps): make `send_maker_payment` async

---

mm2src/coins_activation/src/eth_with_token_activation.rs

without `display_eth_address`
```log
0xAA36D...38cc4
```
with `display_eth_address`
```log
0xAA36D90C59aB32C743C5570476b7676385838cc4
```

fix(evm): correctly display eth addr in iguana v2 activation result

---

mm2src/coins/qrc20/swap.rs
mm2src/mm2_main/src/lp_swap/taker_swap.rs
mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs

To Test:
Nothing as swaps should work as normal after this. This invalidates the fix of this issue https://github.com/KomodoPlatform/komodo-defi-framework/issues/1442 and I will work on a better solution for this where taker rebroadcast thier transaction if it's not on chain.

fix(legacy-swap): remove the need for takers to confirm their payment

---

mm2src/mm2_main/src/lp_swap/maker_swap.rs
mm2src/mm2_main/src/lp_swap/taker_swap.rs

This PR fixes recover funds for taker when the swap was marked as unsuccessful due to the maker payment spend transaction not being confirmed. It also uses the required confirmations from coin config for taker/maker payment spend instead of using 1 confirmation max. This is because some chains require more than 1 confirmation for finality, e.g. Polygon.

fix(legacy-swap): check for confirmations on recover taker

---

mm2src/mm2_test_helpers/src/for_tests.rs

In current dev we use only one url in sepolia endpoints, which is experiencing issues right now:
`Failed to get client version for all urls`
```
failures:
---- mm2_tests::eth_tests::test_sign_eth_transaction stdout ----
04 10:22:29, for_tests:1547] sending rpc request {"userpass":"pass","method":"enable","coin":"ETH","urls":["https://rpc2.sepolia.org/"],"swap_contract_address":"0xeA6D65434A15377081495a9E7C5893543E7c32cB","mm2":1} to http://127.0.0.150:7783/
thread 'mm2_tests::eth_tests::test_sign_eth_transaction' panicked at 'assertion failed: `(left == right)`
left: `500`,
right: `200`: 'enable "ETH"' failed: {"error":"rpc:184] dispatcher_legacy:141] lp_commands_legacy:169] lp_coins:4463] eth:6530] Failed to get client version for all urls"}', …
```

fix(tests): add more sepolia endpoints in tests

---

mm2src/coins/rpc_command/account_balance.rs
mm2src/coins/rpc_command/get_new_address.rs
mm2src/coins/rpc_command/init_account_balance.rs
mm2src/coins/rpc_command/init_create_account.rs
mm2src/coins/rpc_command/init_scan_for_new_addresses.rs
mm2src/coins/utxo/bch.rs
mm2src/coins/utxo/qtum.rs
mm2src/coins/utxo/rpc_clients/electrum_rpc/connection.rs
mm2src/coins/utxo/utxo_common.rs
mm2src/coins/utxo/utxo_standard.rs
mm2src/coins/utxo/utxo_tests.rs
mm2src/coins_activation/src/utxo_activation/common_impl.rs
mm2src/coins_activation/src/utxo_activation/utxo_standard_activation_result.rs
mm2src/mm2_main/tests/integration_tests_common/mod.rs
mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
mm2src/mm2_test_helpers/src/structs.rs

This is to return the same type/json across all coins for GUI since EVM uses `CoinBalanceMap`, the balance for UTXO will show as
```json
"balance":{
"KMD":{
"spendable":"0",
"unspendable":"0"
}
}
```
instead of
```json
"balance":{
"spendable":"0",
"unspendable":"0"
}
```
**To Test:**
Already tested by @CharlVS

fix(hd-wallet): use `CoinBalanceMap` for UTXO and QTUM

---

mm2src/mm2_main/src/rpc/dispatcher/dispatcher_legacy.rs
mm2src/mm2_main/src/rpc/lp_commands/lp_commands_legacy.rs

fix(foot-shooting): remove leftover code that panics via RPC

---

mm2src/coins/rpc_command/get_new_address.rs
mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs

**To Test:**
Nothing as it already tested by @CharlVS. No docs updates as well as the docs show the full address in response.

fix(hd-wallet): correctly display evm addr in `get_new_address` response

---

CHANGELOG.md

chore(release): add changelog entries for v2.2.0-beta

---

.github/workflows/pr-lint.yml
mm2src/common/common.rs
mm2src/mm2_main/src/mm2.rs

Makes KDF to check main files before reading them to prevent potential panics.
**To Test:** @KomodoPlatform/qa 
Start KDF with a path that is a dir or a non-existing path and better error messages will be displayed. Starting using CLI args should work as before and also any existing way of loading mm2 config and coins file should work as before.

improvement(error-handling): main files

---

mm2src/mm2_bitcoin/rpc/src/lib.rs
mm2src/mm2_bitcoin/rpc/src/v1/types/bytes.rs
mm2src/mm2_bitcoin/rpc/src/v1/types/hash.rs

Makes no sense to rely on `core` on KDF.

fix(mm2_bitcoin): don't rely on `core`

---

Cargo.lock
mm2src/mm2_core/Cargo.toml
mm2src/mm2_p2p/Cargo.toml
mm2src/proxy_signature/Cargo.toml

Bumps libp2p to include https://github.com/KomodoPlatform/rust-libp2p/commit/f949f65669f5dbfb95eb38e7e9393b48202c2995 for security reasons.
Fixes #771
Blocker for the [next release](https://github.com/KomodoPlatform/komodo-defi-framework/pull/2284).

chore(libp2p): k-0.52.11 bump

---

mm2src/coins/Cargo.toml
mm2src/mm2_main/Cargo.toml
mm2src/mm2_p2p/Cargo.toml
mm2src/mm2_p2p/src/behaviours/atomicdex.rs

Follow up to https://github.com/KomodoPlatform/komodo-defi-framework/pull/2255
cc @dimxy @mariocynicys

chore(p2p): follow-up nits

---

.docker/Dockerfile
.github/workflows/dev-build.yml
.github/workflows/release-build.yml
.github/workflows/test.yml
docs/WASM_BUILD.md

I was getting errors building current dev branch in both container and local system: 
```
error: failed to compile `wasm-pack v0.13.1`, intermediate artifacts can be found at `/tmp/cargo-installqtfHhI`
Caused by:
package `bumpalo v3.16.0` cannot be built because it requires rustc 1.73.0 or newer, while the currently active rustc version is 1.72.0-nightly
Try re-running cargo install with `--locked`
```
Referring to the [GHA workflow deps](https://github.com/KomodoPlatform/komodo-defi-framework/blob/main/.github/actions/deps-install/action.yml#L19), I noticed a different protoc version so updated it in the Dockerfile.
I also added [rustwasm install from script step from GHA](https://github.com/KomodoPlatform/komodo-defi-framework/blob/main/.github/workflows/dev-build.yml#L371) to avoid the …

chore(ci): Update docker build for wasm

---

.github/workflows/pr-lint.yml
mm2src/mm2_bin_lib/Cargo.toml
mm2src/mm2_main/Cargo.toml

Fixes wasm build with feature flag `test-ext-api`
```
hound@hound:~/komodo-defi-framework$ docker run -v "$(pwd)":/app -w /app kdf-build-container wasm-pack build mm2src/mm2_bin_lib --target web --out-dir wasm_build/deps/pkg/ --features  test-ext-api
[INFO]: Checking for the Wasm target...
info: downloading component 'rust-std' for 'wasm32-unknown-unknown'
info: installing component 'rust-std' for 'wasm32-unknown-unknown'
[INFO]: Compiling to Wasm...
warning: /app/mm2src/mm2_bin_lib/Cargo.toml: file `/app/mm2src/mm2_bin_lib/src/mm2_bin.rs` found to be present in multiple build targets:
* `bin` target `mm2`
* `bin` target `kdf`
error: none of the selected packages contains these features: test-ext-api
Error: Compiling your crate to WebAssembly failed
Caused by: Compiling your crate to …
```

fix(wasm): add test-ext-api feature to mm2_main and mm2_bin_lib tomls

---

.github/actions/build-cache/action.yml
.github/actions/cargo-cache/action.yml
.github/workflows/dev-build.yml
.github/workflows/fmt-and-lint.yml
.github/workflows/release-build.yml
.github/workflows/test.yml
mm2src/coins/eth/eth_tests.rs
mm2src/trading_api/src/one_inch_api/client.rs
mm2src/trading_api/src/one_inch_api/errors.rs

self-explanatory (see commit by commit if it helps)

improvement(CI): switch to proper rust caching

---

Cargo.lock

Cargo.lock needs `web-time` package for `timed-map` after adding `wasm` feature in deps

fix(deps): add the web-time package to Cargo.lock

---

mm2src/mm2_main/src/lp_swap.rs
mm2src/mm2_main/src/lp_swap/maker_swap.rs
mm2src/mm2_main/src/lp_swap/swap_watcher.rs
mm2src/mm2_main/src/lp_swap/taker_restart.rs
mm2src/mm2_main/src/lp_swap/taker_swap.rs
mm2src/mm2_main/src/mm2.rs
mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs

This PR moves payment existence check in `maker_payment`/`send_taker_payment` before timeout validation and skips timeout if payment is already sent, as the taker swap should proceed to waiting for maker to spend the taker payment.
Should fix https://github.com/KomodoPlatform/komodo-defi-framework/issues/2136 , but we are still not aware why the electrum request doesn't timeout.

fix(legacy_swap): check for existing maker/taker payment before timeout

---

mm2src/crypto/src/mnemonic.rs
mm2src/mm2_main/src/lp_wallet.rs

Fixes an issue where passphrases were incorrectly validated as BIP39 mnemonics during storage decryption. Now, passphrases no longer require mnemonic validation.

fix(crypto): allow non bip39 mnemonics storage

---

.dockerignore
.github/workflows/dev-build.yml
.github/workflows/release-build.yml
.gitignore
docs/ANDROID.md
mm2src/mm2_bin_lib/build.rs
mm2src/mm2_bin_lib/src/lib.rs
mm2src/mm2_bin_lib/src/mm2_bin.rs
mm2src/mm2_bin_lib/src/mm2_native_lib.rs
mm2src/mm2_bin_lib/src/mm2_wasm_lib.rs

Previous build script were highly unstable and relied on the `MM_DATETIME` and `MM_VERSION` files which was very annoying. These files caused cargo to invalidate the build cache, so even if you ran `cargo build` multiple times without changing anything, it would still rebuild because the build script triggered cache invalidation.
This PR makes the build script straightforward and more stable without causing cache invalidation. The final versioning output remains as is, but the implementation side is robust than ever. 
Major effects:
- No more cache invalidations.
- The `MM_VERSION` and `MM_DATETIME` files are no longer needed in the project root.
- Datetime handling is now more stable. Previously `MM_DATETIME` file could become outdated as it wasn't consistently updated.

refactor(build script): rewrite the main build script

---

Cargo.lock
mm2src/mm2_core/Cargo.toml
mm2src/mm2_p2p/Cargo.toml
mm2src/proxy_signature/Cargo.toml

Bumps libp2p from `k-0.52.11` to `k-0.52.12` to fix build problems on IOS platform.

chore(dep-bump): libp2p

---

mm2src/mm2_main/src/lp_native_dex.rs
mm2src/mm2_main/src/lp_swap.rs
mm2src/mm2_main/src/lp_swap/maker_swap.rs
mm2src/mm2_main/src/lp_swap/taker_swap.rs

this field was convereted to a hashmap instead of a vector for easy access to the swap. also we now manually delete the swap from running swaps when the swap is finished~/inturepted~ (memory leak fix). as a consequence to manuallly deleting the swap from running_swaps, we can now store them as arcs instead of weakrefs, which simplifies a lot of `.upgrade()` calls.
~blocked on its base #2280~ re-fixed on top of `dev` instead

fix(mem-leak): `running_swap` never shrinks

---

mm2src/coins/hd_wallet/withdraw_ops.rs
mm2src/coins/lp_coins.rs
mm2src/coins/rpc_command/tendermint/staking.rs
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/coins/tendermint/tendermint_token.rs
mm2src/coins/tendermint/tendermint_tx_history_v2.rs
mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
mm2src/mm2_main/tests/docker_tests/tendermint_tests.rs
mm2src/mm2_test_helpers/src/for_tests.rs

Adds tendermint protocol support on `add_delegation` RPC, and extends tendermint transaction history implementation to support delegation transactions.
Next is to do the same for undelegation on `remove_delegation`.
TODO: File a documentation issue on https://github.com/KomodoPlatform/komodo-docs-mdx

feat(tendermint): staking/delegation

---

mm2src/coins/utxo/utxo_withdraw.rs

This fixes `task::withdraw::init` for non-trezor utxo withdraws as it was failing with `"error_data": "NoTrezorDeviceAvailable"`
**To Test:**
Make sure `task::withdraw::init` works fine for iguana/hd wallet/trezor

fix(utxo-withdraw): get hw ctx only when `PrivKeyPolicy` is trezor

---

mm2src/coins/lp_coins.rs
mm2src/coins/rpc_command/tendermint/staking.rs
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/coins/tendermint/tendermint_tx_history_v2.rs
mm2src/mm2_main/tests/docker_tests/tendermint_tests.rs
mm2src/mm2_test_helpers/src/for_tests.rs

Adds tendermint protocol support on `remove_delegation` RPC, and extends tendermint transaction history implementation to support undelegate transactions.
Next is to add staking listing RPCs for delegations, undelegations (with claiming period informations), rewards, etc.

feat(tendermint): unstaking/undelegation

---

mm2src/mm2_main/src/database.rs
mm2src/mm2_main/src/database/my_swaps.rs
mm2src/mm2_main/src/lp_ordermatch.rs
mm2src/mm2_main/src/lp_ordermatch/my_orders_storage.rs
mm2src/mm2_main/src/lp_ordermatch/new_protocol.rs
mm2src/mm2_main/src/lp_swap/maker_swap_v2.rs
mm2src/mm2_main/src/lp_swap/swap_v2_rpcs.rs
mm2src/mm2_main/src/lp_swap/taker_swap_v2.rs
mm2src/mm2_main/src/mm2.rs
mm2src/mm2_main/src/ordermatch_tests.rs
mm2src/mm2_main/src/swap_versioning.rs

ref issue https://github.com/KomodoPlatform/komodo-defi-framework/issues/2337
ordermatch structs which got swap_version field:
- TakerOrderBuilder
- MakerOrderBuilder
- MakerOrder
- MakerReserved
- TakerRequest
swap structs. if swap started swap_version will be saved in db:
- MySwapForRpc
- TakerSwapStateMachine
- MakerSwapStateMachine
- TakerSwapDbRepr
- MakerSwapDbRepr
swap version 2 is tpu v2 protocol
legacy swap protocol is 1 version
When Taker or Maker **build** order, the value `const SWAP_VERSION: u32 = 2;` is used for order **Builder**. 
However in `create_maker_order`/`lp_auto_buy` if user didnt use `ctx.use_trading_proto_v2()` in config we set legacy protocol version to the order.

feat(tpu-v2): provide swap protocol versioning

---

mm2src/mm2_io/src/fs.rs
mm2src/mm2_main/src/lp_wallet/mnemonics_storage.rs

By default, `get_wallet_names` returns not only `*.dat` filenames from `db_root` as wallet names but also directories. For example, if we create a `l.dat` **folder** in `db_root`, it will be included in the wallet names list, like this:  
```json
{
"mmrpc": "2.0",
"result": {
"wallet_names": [
"l",
"decker",
"hello"
],
"activated_wallet": "decker"
},
"id": null
}
```
The current implementation is not necessarily ideal. Maybe we should perform this check (i.e., ensuring it’s a file and not a directory) directly in `filter_files_by_extension`. But my primary goal was to avoid modifying existing file-related functions.

fix(fs): make `filter_files_by_extension` return only files

---

mm2src/coins/coin_errors.rs
mm2src/coins/eth.rs
mm2src/coins/eth/eth_swap_v2/eth_maker_swap_v2.rs
mm2src/coins/eth/eth_swap_v2/eth_taker_swap_v2.rs
mm2src/coins/eth/eth_swap_v2/mod.rs
mm2src/coins/eth/nft_swap_v2/mod.rs
mm2src/coins/lp_coins.rs

**Note:** This PRs updates eth TPU part.
This PR covers this issue https://github.com/KomodoPlatform/komodo-defi-framework/issues/2328 in eth tpu functionality.
- The payment status (`PaymentSent`) check has been removed from TPU validation payment functionality for all ETH implementations, including taker, maker, and maker-nft https://github.com/KomodoPlatform/komodo-defi-framework/pull/2334/commits/7be74aa788de9cd7d268132d1b963688304425bc. 
It is done to avoid unnecessary loops of checking  `PaymentSent` in KDF code, as we already explicitly wait for taker/maker payment transaction confirmations in TPU (see `wait_for_confirmations` function). If tx confirmation failed, it would mean that payment doesnt have `PaymentSent`state in smart contract.
Additionally this check is handled in …

fix(eth-tpu): remove state from funding validation

---

mm2src/coins/lp_coins.rs
mm2src/coins/my_tx_history_v2.rs
mm2src/coins/rpc_command/tendermint/staking.rs
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/coins/tendermint/tendermint_tx_history_v2.rs
mm2src/coins_activation/src/tendermint_with_assets_activation.rs
mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
mm2src/mm2_test_helpers/dummy_files/nucleus-history.json

Adds new RPC `claim_staking_rewards` with a support of tendermint protocol along with tx history support on tendermint claiming rewards.
Next is to add listing/querying RPCs.

feat(tendermint): claim delegation rewards

---

mm2src/coins/lp_coins.rs
mm2src/coins/rpc_command/tendermint/staking.rs
mm2src/coins/utxo/qtum_delegation.rs
mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
mm2src/mm2_test_helpers/src/for_tests.rs

This PR re-organizes staking-related RPC methods under a single namespace called `staking`, and marks them as `experimental`. The changes made aim to improve consistency and future extensibility within the staking module.
The following RPC methods have been renamed to align with a more structured namespace:
- **`add_delegation`** → **`experimental::staking::delegate`**
- **`remove_delegation`** → **`experimental::staking::undelegate`**
- **`get_staking_infos`** → **`experimental::staking::query::delegations`**
The request payload for `get_staking_infos` (now `experimental::staking::query::delegations`) has been updated.
**Previous Format:**
```json
{
"userpass": "pass",
"mmrpc": "2.0",
"method": "get_staking_infos",
"params": {
"coin": "tQTUM"
},
"id": 0
}
```
**Updated Format:**
```json …
```

improvement(RPCs): group staking rpcs under a namespace

---

mm2src/coins/tendermint/tendermint_coin.rs

`tendermint_coin::test_claim_staking_rewards` sometimes fails because the actual reward amount increases while the test is running. This PR stabilizes the coverage logic.
Example failure: https://github.com/KomodoPlatform/komodo-defi-framework/actions/runs/13543733711/job/37850426342?pr=2372#step:6:435

fix(tests): stabilize `tendermint_coin::test_claim_staking_rewards`

---

mm2src/crypto/src/encrypt.rs
mm2src/crypto/src/key_derivation.rs
mm2src/crypto/src/mnemonic.rs

Previously, the key derivation function for mnemonic password always used `Argon2::default()`, which depends on the
library’s default parameters. Since those defaults may change over time (e.g., following changes
in OWASP recommendations), this PR ensures that the Argon2 instance is built using the
parameters stored in the keystore file. This prevents breaks in mnemonic decryption when updating the Argon2 crate.
Additionally, a version field was added to the `EncryptedData` struct to enable easier handling of backward compatibility.
fixes https://github.com/KomodoPlatform/komodo-defi-framework/issues/2341

fix(key-derivation): use stored Argon2 parameters instead of default values

---

.github/workflows/dev-build.yml
.github/workflows/release-build.yml
mm2src/mm2_main/src/lp_swap.rs
mm2src/mm2_main/src/lp_swap/saved_swap.rs

This adds an additional field for the `my_swap_status` RPC response for v1/legacy swaps. This field is only included if the swap is finished and is successful.

feat(rpc): add is_success field to legacy MySwapStatusResponse

---

mm2src/coins/tendermint/tendermint_coin.rs

Using ABCI query with `GetTxsEventRequest` fails on certain networks like Iris and Osmosis due to some breaking changes on the remote nodes. Refactored those parts to use `TxSearchRequest` as it seems more stable and doesn't have deprecated fields.

refactor(tx-query): use `TxSearchRequest` for tx queries

---

.github/workflows/fmt-and-lint.yml

The `--component` flag in rustup commands was using incorrect syntax when specifying multiple components. This caused CI failures with the error `invalid value 'clippy' for '[TOOLCHAIN]...': invalid toolchain name: 'clippy'`.

fix(ci): use correct rustup component syntax in fmt-and-lint job

---

mm2src/coins/lp_coins.rs
mm2src/coins/rpc_command/tendermint/staking.rs
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
mm2src/mm2_main/tests/docker_tests/tendermint_tests.rs
mm2src/mm2_test_helpers/src/for_tests.rs

Implements `delegations` and `ongoing_undelegations` searching RPCs including rewards and undelegation completion period information for tendermint.

feat(tendermint): staking queries

---

mm2src/coins/tendermint/tendermint_tx_history_v2.rs
mm2src/common/log.rs

Fixes https://github.com/KomodoPlatform/komodo-defi-framework/issues/2347

fix(tx-history): fix unhandled IBC and HTLC events

---

Cargo.lock
mm2src/mm2_main/src/lp_native_dex.rs
mm2src/mm2_main/src/lp_network.rs
mm2src/mm2_main/src/lp_stats.rs
mm2src/mm2_net/src/ip_addr.rs
mm2src/mm2_net/src/lib.rs
mm2src/mm2_p2p/Cargo.toml
mm2src/mm2_p2p/src/network.rs

It's dangerous to hard-code IPs statically because they can become outdated. In fact, with this change, I was able to discover that 'falkor.dragon-seed.com' corresponds to the IP '65.108.252.86', not '168.119.237.8' and 'fr1.cipig.net' is an unavailable node.

improvement(network): remove static IPs from seed lists

---

mm2src/coins/utxo/utxo_tests.rs

~~Couldn't find an electrum with a version other than 1.4 here https://1209k.com/bitcoin-eye/ele.php (for all coins not only btc) so decided to ignore the failing test as there is no way to fix it.~~
Did this https://github.com/KomodoPlatform/komodo-defi-framework/pull/2412#issuecomment-2795848462 instead

test(electrums): fix failing test_one_unavailable_electrum_proto_version

---

mm2src/coins/lp_price.rs

This PR also removes Nomics as it was shutdown. Fixes https://github.com/KomodoPlatform/komodo-defi-framework/issues/2403
This is a quick fix for https://github.com/KomodoPlatform/komodo-defi-framework/issues/2403 but a subsequent PR should remove this hardcoded providers and allow setting them through either config or request.

fix(makerbot): add LiveCoinWatch price provider

---

mm2src/coins/utxo/qtum.rs
mm2src/coins/utxo/qtum_delegation.rs
mm2src/coins/utxo/utxo_tests.rs
mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs

Addressing https://github.com/KomodoPlatform/komodo-docs-mdx/issues/428#issuecomment-2818166149. I think it's fine to not accept `address` anymore as this RPC uses `experimental` prefix, but I can also do that if you think otherwise.
cc @smk762

chore(RPC): use consistent param name for QTUM delegation

---

mm2src/coins/eth.rs

It uses the enabled address to withdraw for now, fixes https://github.com/KomodoPlatform/komodo-defi-framework/issues/2421

fix(evm): make `withdraw_nft` work in HD mode

---

mm2src/coins/utxo/rpc_clients/electrum_rpc/client.rs
mm2src/coins/utxo/rpc_clients/electrum_rpc/connection_manager/manager.rs
mm2src/coins/utxo/utxo_balance_events.rs

We need to initially register the addresses we wanna get balance notification for. We used to do that in the past at coin enablement time (since event streaming config was static and doesn't change at runtime), that was removed since it doesn't make sense with runtime enabled/disabled streaming. But was never replaced with the appropriate logic to register these addresses once the *streamer was enabled*.
This PR register our addresses with the event streamer on initialization so it could track them.

fix(event-streaming): initial addresses registration in utxo balance streaming

---

CHANGELOG.md

Adds changelogs for latest commits that were not included in https://github.com/KomodoPlatform/komodo-defi-framework/pull/2415

chore(release): complete v2.4.0-beta changelogs

---

Cargo.lock

Bumps to [`timed-map@1.3.1`](https://github.com/ozmann-industries/timed-map/releases/tag/v1.3.1), which is the latest release.

deps(timed-map): bump to `1.3.1`

---

mm2src/coins/eth/eth_balance_events.rs

as using `.to_string()` truncates the address and adds some weird dots inbetween that doesn't encode very well in SSE.
fixes https://github.com/KomodoPlatform/komodo-docs-mdx/pull/457/#discussion_r2073010086
.

fix(eth-balance-events): serialize eth address using AddrToString

---

Cargo.lock
mm2src/coins/Cargo.toml
mm2src/mm2_core/Cargo.toml
mm2src/mm2_main/Cargo.toml
mm2src/mm2_main/src/lp_swap.rs
mm2src/mm2_main/src/lp_swap/pubkey_banning.rs
mm2src/mm2_p2p/Cargo.toml

Implements expirable public key banning. For swaps public keys will be banned for one hour, which should be a sufficient penalty (and can be easily increased if needed). Manual bans will default to permanent but this can be changed by including the `duration_min` parameter in the request.
Fixes https://github.com/KomodoPlatform/komodo-defi-framework/issues/1985
Docs issue: https://github.com/KomodoPlatform/komodo-docs-mdx/issues/491

feat(pubkey-banning): expirable bans

---

.github/workflows/dev-build.yml
.github/workflows/release-build.yml
mm2src/mm2_bin_lib/Cargo.toml

It's been a long time since we did the renaming. We kept the old name to avoid breaking the existing build flow for downstream users. Since it's been quite a while, they should have already migrated to the new name. We can't keep these old artifacts forever, so let's remove them now.

chore(build-artifacts): remove duplicated mm2 build artifacts

---

mm2src/mm2_main/src/rpc.rs
mm2src/mm2_main/src/rpc/dispatcher/dispatcher_legacy.rs
mm2src/mm2_main/tests/mm2_tests/lightning_tests.rs
mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs

Allows using any (legacy or current) RPC methods without needing to include `mmrpc` in the RPC payloads. It has been annoying to constantly add and remove that field between different RPCs. With this PR, we can leave it to KDF and it will handle it automatically. Ideally, we should remove it entirely from the codebase but that would cause breaking change for downstreams.

improvement(RPC): unified interface for legacy and current RPC interfaces

---

Cargo.lock
Cargo.toml

Bumps to [`timed-map@1.4.1`](https://github.com/ozmann-industries/timed-map/releases/tag/v.1.4.1), which fixes https://github.com/KomodoPlatform/komodo-defi-framework/issues/2478.

deps(timed-map): bump to 1.4.1

---

mm2src/coins/eth/eth_balance_events.rs
mm2src/coins/eth/fee_estimation/eth_fee_events.rs
mm2src/coins/tendermint/tendermint_balance_events.rs
mm2src/coins/utxo/tx_history_events.rs
mm2src/coins/utxo/utxo_balance_events.rs
mm2src/coins/z_coin/tx_history_events.rs
mm2src/coins/z_coin/tx_streaming_tests/native.rs
mm2src/coins/z_coin/z_balance_streaming.rs
mm2src/mm2_core/src/data_asker.rs
mm2src/mm2_event_stream/src/event.rs
mm2src/mm2_event_stream/src/lib.rs
mm2src/mm2_event_stream/src/manager.rs
mm2src/mm2_event_stream/src/streamer.rs
mm2src/mm2_event_stream/src/streamer_ids.rs
mm2src/mm2_main/src/heartbeat_event.rs
mm2src/mm2_main/src/lp_ordermatch.rs
mm2src/mm2_main/src/lp_ordermatch/order_events.rs
mm2src/mm2_main/src/lp_ordermatch/orderbook_events.rs
mm2src/mm2_main/src/lp_swap/maker_swap.rs
mm2src/mm2_main/src/lp_swap/maker_swap_v2.rs
mm2src/mm2_main/src/lp_swap/swap_events.rs
mm2src/mm2_main/src/lp_swap/taker_swap.rs
mm2src/mm2_main/src/lp_swap/taker_swap_v2.rs
mm2src/mm2_main/src/rpc/streaming_activations/disable.rs
mm2src/mm2_main/src/rpc/streaming_activations/mod.rs
mm2src/mm2_p2p/src/application/network_event.rs
mm2src/rpc_task/src/manager.rs

(#2207): Refactored the Streamer Id to its own enumeration type.

improvement(event-streaming): strong type streamer IDs

---

mm2src/mm2_net/src/ip_addr.rs

Currently, KDF expects the first result of the IP resolution to be an IPv4 address as it does not support IPv6 addresses. This assumption can cause a problem if the first result is an IPv6 address which makes KDF to panic on startup. With this patch, instead of immediately failing on the first IPv6 result, KDF now iterates through all results and only fails if no IPv4 address is found.

fix(dns): better ip resolution

---

mm2src/mm2_main/src/lp_native_dex.rs

We should call `WalletConnectCtx::from_ctx` only when necessary not during the KDF startup.
Currently, it seems like we are already calling it in several places:
Each of these calls attempts to initialize the `WalletConnection`, meaning the startup call is unnecessary. If something breaks, it indicates that we are missing the `WalletConnectCtx::from_ctx` call somewhere in the WalletConnect logic.
Fixes #2484

fix(startup): don't initialize WalletConnect during startup

---

mm2src/coins/tendermint/htlc/mod.rs
mm2src/coins/tendermint/tendermint_coin.rs
mm2src/coins/tendermint/tendermint_token.rs
mm2src/coins_activation/src/tendermint_token_activation.rs
mm2src/coins_activation/src/tendermint_with_assets_activation.rs
mm2src/mm2_main/src/lp_ordermatch.rs
mm2src/mm2_main/src/lp_ordermatch/my_orders_storage.rs
mm2src/mm2_main/src/lp_swap/maker_swap.rs
mm2src/mm2_main/src/lp_swap/recreate_swap_data.rs
mm2src/mm2_main/src/lp_swap/taker_swap.rs
mm2src/mm2_main/src/ordermatch_tests.rs
mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
mm2src/mm2_test_helpers/src/electrums.rs
mm2src/mm2_test_helpers/src/for_tests.rs

The continuation of [feat(ibc-routing-part-1): supporting entire Cosmos network for swaps #2459](https://github.com/KomodoPlatform/komodo-defi-framework/pull/2459).
The items that are implemented in this part include:
1. Adds a new field `order_metadata`, to the taker and maker order types used at the pre-swap stage. This field is intended to store information unrelated to users specifically (e.g. swap version, protocol details, etc.), which also includes IBC channel information for non-HTLC Tendermint swaps. This information will be used to validate IBC channels before starting the swap process ([see here](https://github.com/KomodoPlatform/komodo-defi-framework/blob/db06a3b2ff9a83bc92d9cca759f5914749df9dea/mm2src/mm2_main/src/lp_ordermatch.rs#L3094-L3104) and …

feat(ibc-routing-part-2): supporting entire Cosmos network for swaps

---

mm2src/coins/utxo/utxo_common.rs

The removed logic is quite unnecessary today. With this patch, the minimum trading volume becomes 0.0001, which is around the equivalent of 10 USD and is roughly 10 times the average transaction fee on the BTC network.
Closes #2480 and #1935
cc @cipig

improvement(orders): remove BTC specific volume from min_trading_vol logic

---

mm2src/kdf_walletconnect/src/connection_handler.rs
mm2src/kdf_walletconnect/src/lib.rs

This PR fixes a critical race condition in the WalletConnect module that causes `Client(WebsocketClient(NotConnected))` errors during initialization, particularly for the `wc_new_connection` RPC call.
As reported in https://github.com/KomodoPlatform/komodo-defi-framework/issues/2505, network operations could be attempted before the WebSocket connection was fully established or immediately after it was dropped. This resulted in an immediate failure with the following error, instead of returning a valid session URL:
```json
{
"error": "Subscription Error: Client(WebsocketClient(NotConnected))",
"error_type": "SessionRequestError"
}
```
This was a regression traced back to recent changes in https://github.com/KomodoPlatform/komodo-defi-framework/pull/2485 that decoupled WalletConnect …

fix(walletconnect): centralize connection and retry logic

---

mm2src/coins/eth.rs
mm2src/coins/lp_coins.rs

This change improves the error handling for EVM withdrawals when the provided EIP-1559 `max_fee_per_gas` is too low. Previously, the API returned a generic string-based error, forcing the user to guess a new fee. Now, the withdraw endpoint can return a structured error object containing the required network base fee, allowing client applications to better handle the error.
Not all web3 RPC nodes return this detailed information. For nodes that reject the transaction without specifics, a more generic `InvalidFee` error is returned, indicating that the fee was too low but without providing the required value. In such case, clients should use fee estimator again to get a more up to date value.
```json
{
"error": "Invalid fee parameters: Provided gas fee cap is less than the required network …
```

fix(eth): propagate structured EIP-1559 fee errors

---

.docker/Dockerfile.ci-container
mm2src/coins/z_coin/storage/blockdb/blockdb_idb_storage.rs

I missed the WASM problem while reviewing https://github.com/KomodoPlatform/komodo-defi-framework/pull/2489 (CI is not being properly run on external PRs :/).
Also, `komodoofficial/ci-container` image has been updated to use Debian 11 as LTS support for Debian 10 has ended and it is no longer working in the CI environment.

fix(WASM and Debian): fix build failures

---

docs/DEV_ENVIRONMENT.md

Improve the docker test start failure note on @onur-ozkan review 
(gpt was used to fix it)

fix(DOC): improve docker tests start doc

---

mm2src/coins/rpc_command/offline_keys.rs
mm2src/mm2_bin_lib/Cargo.toml

Before:
```json
{
"derivation_path": "m/44'/60'/0/0/1",
"pubkey": "03de36fe6b0b1eaea7447e4bb3a56c8755fd5cf5d3fd9885a0582c99777229052e",
"address": "0x49f4a1c47579d9603100fc50e227079794335f20",
"priv_key": "0xe6a0f10b28192d2823433ec7121633c5d85239799b50e1e93280d000ad6a1341"
}
```
After
```json
{
"derivation_path": "m/44'/60'/0/0/1",
"pubkey": "0xde36fe6b0b1eaea7447e4bb3a56c8755fd5cf5d3fd9885a0582c99777229052e1b7019075669c5d65d4878b3db06e0b534159b0ba762714737677711b3375a3f",
"address": "0x49F4A1c47579d9603100Fc50e227079794335f20",
"priv_key": "0xe6a0f10b28192d2823433ec7121633c5d85239799b50e1e93280d000ad6a1341"
}
```
`0x49f4a1c47579d9603100fc50e227079794335f20` -> 0x49**F**4**A**1c47579d9603100**F**c50e227079794335f20
Output was validated against web3.py using the script below:
```py
from …
```

fix(evm): support EIP55 (mixed case) & uncompressed pubkey exports

---

mm2src/kdf_walletconnect/src/lib.rs
mm2src/kdf_walletconnect/src/session/mod.rs
mm2src/mm2_main/src/rpc/wc_commands/new_connection.rs

Currently when creating a new WalletConnect connection, you get back only the pairing url. It's now made so it returns also the pairing topic along.
The flow from the GUI would be like this:
- hit `new_connection` -> receive `{ "url": "wc:40923091...", "pairing_topic": "40923091..." }`
- keep hitting `get_session` till the user has established the session:
- request `{ "topic": "40923091...", "with_pairing_topic": true }`
- keep requesting till getting a non `null` response. Only then, the session has been established.
- any subsequent requests to `get_session` should use the `session_topic` instead of `pairing_topic` (the `pairing_topic` should be discarded really at this point). And `"with_pairing_topic"` should be set to `false` (or left out to default to `false`) for performance …

improvement(walletconnect): return the `pairing_topic` in `new_connection` response
