- mm2src/README.md
- mm2src/helpers/log.rs
- mm2src/mm2.rs
- mm2src/rpc/commands.rs
@artemii235 , please take a look, I wonder whether [UTXO](https://github.com/artemii235/SuperNET/issues/157) is a subset of the "_A more transparent operation, telling user what's going on and what went wrong_" goal or if maybe it needs a separate mention.
> Refresh the port goals

- mm2src/coins/utxo.rs
- mm2src/coins/utxo/rpc_clients.rs
- mm2src/common/common.rs
A kind of round-robin redundancy. Wait until Electrum server recognizes
that UTXOs are spent before allowing to send another transaction.
> #254 Send Electrum request to additional servers only when prev fails.

- iguana/exchanges/LP_include.h
- iguana/exchanges/LP_nativeDEX.c
- mm2src/common/mm_ctx.rs
- mm2src/lp_native_dex.rs
- mm2src/mm2.rs
- mm2src/peers/peers_tests.rs
- mm2src/rpc.rs
> Fallbacks in myipaddr detection

- mm2src/coins/lp_coins.rs
> Enable electrum from conf and defaults

- mm2src/common/common.rs
- mm2src/lp_ordermatch.rs
- mm2src/lp_swap.rs
- mm2src/peers/peers.rs
> UUID, checksum salt, DHT traces, verbose timeout

- mm2src/mm2_tests.rs
- mm2src/peers/peers.rs
> Skip finished gets

- mm2src/common/for_tests.rs
- mm2src/mm2.rs
- mm2src/mm2_tests.rs
- mm2src/rpc.rs
- mm2src/rpc/lp_commands.rs
The userpass will be removed in favor of it later.
> #298 Add rpc_password field to JSON config.

- .cargo/config
- Cargo.toml
- iguana/exchanges/LP_coins.c
- iguana/exchanges/LP_include.h
- iguana/exchanges/LP_nativeDEX.c
- iguana/exchanges/LP_scan.c
- iguana/exchanges/LP_utxo.c
- marketmaker_build_depends.cmd
- mm2src/common/common.rs
- mm2src/crash_reports.rs
- mm2src/lp_native_dex.rs
- mm2src/lp_network.rs
- mm2src/lp_ordermatch.rs
- mm2src/lp_swap.rs
- mm2src/mm2.rs
- mm2src/mm2_bin.rs
- mm2src/mm2_lib.rs
- mm2src/mm2_tests.rs
- mm2src/peers/peers.rs
- mm2src/rpc.rs
- mm2src/rpc/lp_commands.rs
@artemii235 , I've experimentally backported a couple of patches with
```
git clone git@github.com:artemii235/SuperNET.git -b mm2
cd SuperNET
git fetch $url $branch:$branch
git checkout -b mm2-backport
git cherry -v mm2-backport $branch
NB: When there's a conflict, use the original commit message when commiting the fixed version!
git cherry-pick f615d29f670ad605da772b744703d9be7966d1d9
git cherry-pick bb94f1b548c68e6b9fead3f1505c8f963878dee1
git cherry-pick e8d3154eca60c495cbfeae2be998e28893eea756
git cherry-pick 204af4ad48ffe09ff22c0f16171bc1c36771b46d
git cherry-pick dd8ecefc5d212b963bb53902ee5083c5c882e17c
git cherry-pick abb750d5698fe209a6e3ff55fe4e3f5e83e86c1a
git cherry-pick 0f0ce66a9bb5b512328d1827a812d8798294408e
```
~~Can you please take this over and merge into mm2 where …
> Mm2 backport

- iguana/exchanges/LP_include.h
- mm2src/coins/lp_coins.rs
- mm2src/coins/utxo.rs
- mm2src/common/common.rs
- mm2src/mm2_tests.rs
> Use the wallet rpcport

- mm2src/lp_ordermatch.rs
- mm2src/mm2_tests.rs
It fixes orderbook when a node has several orders for 1 pair #511
>  Add uuid field to PricePingRequest. 

- mm2src/coins/utxo.rs
- mm2src/coins/utxo/utxo_tests.rs
* Add test that recreates the error
* Add zero input transaction checking
> Fix UTXO get_tx_details_by_hash fails on coinbase transactions. #587

- mm2src/common/mm_number.rs
* Implement handwritten deserialization
* Add tests for the deserialization
> Make MmNumber a wrapper of BigRation #608

- .gitignore
- mm2src/common/.vscode/settings.json
- mm2src/common/Cargo.toml
- mm2src/common/build.rs
- mm2src/common/common.rs
- mm2src/lp_native_dex.rs
- mm2src/mm2.rs
- mm2src/rpc.rs
- mm2src/rpc/lp_commands.rs
Backported from mm2-cross.
cf. https://github.com/ca333/komodoDEX/commit/0ec37f62e438d0ce93a5e7c3ad46ac7eb7aec885#diff-25cd613e5871eb849d702d2ac78f9aecR431,
https://github.com/ca333/komodoDEX/pull/724#issuecomment-613786547
> Add MM_DATETIME into version output

- mm2src/coins/eth.rs
- mm2src/coins/lp_coins.rs
- mm2src/coins/test_coin.rs
- mm2src/coins/utxo.rs
- mm2src/common/big_int_str.rs
- mm2src/common/mm_number.rs
- mm2src/docker_tests.rs
- mm2src/lp_ordermatch.rs
- mm2src/lp_swap.rs
- mm2src/lp_swap/maker_swap.rs
- mm2src/lp_swap/taker_swap.rs
- mm2src/mm2_tests.rs
- mm2src/rpc.rs
- mm2src/rpc/lp_commands.rs
Also use MmNumber to track the virtually locked amount #634
> Refactor balance checks upon order creation and swap start #630

- mm2src/lp_ordermatch.rs
- mm2src/mm2_tests.rs
* Add 'is_mine' field to the OrderbookEntry
* Add test_orderbook_is_mine_orders test
> Add 'is_mine' field to the orderbook response #669

- azure-pipelines-release-stage-job.yml
Adds the library version of MM2 into the Linux and Windows packages for Debug and Release
Not tested as I don't have access to an AZURE account
For issue https://github.com/KomodoPlatform/atomicDEX-API/issues/696
> Add libMM2 for Linux/Windows

- Cargo.lock
- Cargo.toml
- mm2src/gossipsub/src/behaviour.rs
- mm2src/lp_network.rs
- mm2src/lp_ordermatch.rs
- mm2src/mm2_libp2p/src/atomicdex_behaviour.rs
- mm2src/mm2_libp2p/src/atomicdex_behaviour/tests.rs
- mm2src/ordermatch_tests.rs
Add a functional to request an orderbook from relay nodes.
* Remove handle_peer_subscribed, the orderbook will be requested manualy instead
* Add request_relays to collect responses of relays
* Optimize the local orderbook container
> Libp2p request orderbook

- Cargo.lock
- Cargo.toml
- mm2src/docker_tests.rs
- mm2src/gossipsub/src/behaviour.rs
- mm2src/gossipsub/src/behaviour/tests.rs
- mm2src/lp_ordermatch.rs
- mm2src/lp_ordermatch/new_protocol.rs
- mm2src/lp_ordermatch/order_requests_tracker.rs
- mm2src/mm2_bin.rs
- mm2src/mm2_lib.rs
Make not more than 5 requests per second to each peer.
> Limit the number of order requests from other peers.

- mm2src/lp_network.rs
- mm2src/lp_ordermatch.rs
- mm2src/ordermatch_tests.rs
* Add missed test_process_get_order_request test
> Remove extra P2P request and response signing

- mm2src/database.rs
- mm2src/database/stats_swaps.rs
- mm2src/lp_swap.rs
- mm2src/lp_swap/maker_swap.rs
- mm2src/lp_swap/taker_swap.rs
> Index swap statistics to SQLite database #799

- Cargo.lock
- mm2src/coins/eth.rs
- mm2src/coins/eth/eth_tests.rs
- mm2src/coins/lp_coins.rs
- mm2src/coins/qrc20.rs
- mm2src/coins/qrc20/qrc20_tests.rs
- mm2src/coins/test_coin.rs
- mm2src/coins/utxo.rs
- mm2src/coins/utxo/qtum.rs
- mm2src/coins/utxo/utxo_common.rs
- mm2src/coins/utxo/utxo_standard.rs
- mm2src/coins/utxo/utxo_tests.rs
- mm2src/common/Cargo.toml
- mm2src/common/mm_number.rs
- mm2src/docker_tests.rs
- mm2src/docker_tests/qrc20_tests.rs
- mm2src/lp_ordermatch.rs
- mm2src/lp_swap.rs
- mm2src/lp_swap/maker_swap.rs
- mm2src/lp_swap/taker_swap.rs
* Take into account the fee approximation stage to prevent unexpected commission increase
* Add `txfee_volatility_percent` into UTXO coin config
> Fix the balance checking at the start of swap

- mm2src/coins/eth.rs
- mm2src/coins/lp_coins.rs
- mm2src/coins/qrc20.rs
- mm2src/coins/test_coin.rs
- mm2src/coins/utxo/qtum.rs
- mm2src/coins/utxo/utxo_common.rs
- mm2src/coins/utxo/utxo_standard.rs
- mm2src/common/header.rs
- mm2src/docker_tests.rs
- mm2src/docker_tests/qrc20_tests.rs
- mm2src/lp_native_dex.rs
- mm2src/lp_network.rs
- mm2src/lp_ordermatch.rs
- mm2src/lp_swap.rs
- mm2src/lp_swap/maker_swap.rs
- mm2src/lp_swap/taker_swap.rs
- mm2src/mm2_tests.rs
- mm2src/ordermatch_tests.rs
- mm2src/rpc.rs
- mm2src/rpc/lp_commands.rs
> Pass coin dust to dex fee amount

- mm2src/coins/qrc20.rs
- mm2src/coins/utxo.rs
- mm2src/coins/utxo/utxo_common.rs
- mm2src/coins/utxo/utxo_tests.rs
> Add TxFee::FixedPerKb and use it for DOGE.

- mm2src/lp_ordermatch.rs
- mm2src/mm2_tests.rs
- mm2src/ordermatch_tests.rs
> Add min_volume arg to buy and sell RPCs.

- mm2src/lp_ordermatch.rs
- mm2src/lp_ordermatch/orderbook_depth.rs
- mm2src/mm2_tests.rs
- mm2src/mm2_tests/structs.rs
- mm2src/rpc.rs
> Add orderbook_depth RPC.

- Cargo.lock
- mm2src/coins/utxo/utxo_common.rs
- mm2src/coins/utxo/utxo_tests.rs
Closes #843 
Related commits in underlying dep:
https://github.com/artemii235/parity-bitcoin/commit/9fb71d2a6d1b3ad7b83b89ef295645380af36289
https://github.com/artemii235/parity-bitcoin/commit/8eb61445ff6c8e321d945c348798c0f354a9d44d
> Support AuxPOW block header (DOGE). CanRefundHtlc::HaveToWait max 1 hour.

- mm2src/common/mm_number.rs
- mm2src/docker_tests.rs
- mm2src/lp_swap.rs
- mm2src/lp_swap/maker_swap.rs
- mm2src/lp_swap/taker_swap.rs
* Add the `price` field to the `trade_preimage` RPC request
* Add the `result.total_fees` field to the `trade_preimage` RPC response
* Add the `result.taker_fee.coin` filed
> Fix and refactor the `trade_preimage` RPC call

- mm2src/coins/eth.rs
- mm2src/coins/eth/eth_tests.rs
> fix hardcoded "ETH" in withdraw fee_details

- Cargo.lock
- mm2src/coins/utxo/utxo_tests.rs
> Fix waiting for FIRO atomic swap payments refunds.

- Cargo.lock
- mm2src/coins/qrc20.rs
- mm2src/coins/utxo.rs
- mm2src/coins/utxo/qtum.rs
- mm2src/coins/utxo/utxo_common.rs
- mm2src/coins/utxo/utxo_standard.rs
- mm2src/coins/utxo/utxo_tests.rs
Ensure that p2sh spending tx locktime is below the MTP.
#843 #921
> Fix Syscoin indefinite refund wait.

- mm2src/database/stats_swaps.rs
- mm2src/mm2_tests.rs
> Use separate sql statement to avoid stats_swap migration_2 failures.

- mm2src/coins/eth.rs
- mm2src/coins/eth/eth_tests.rs
- mm2src/coins/eth/eth_wasm_tests.rs
- mm2src/coins/lp_coins.rs
- mm2src/coins/qrc20.rs
- mm2src/coins/qrc20/history.rs
- mm2src/coins/qrc20/qrc20_tests.rs
- mm2src/coins/test_coin.rs
- mm2src/coins/utxo/qtum.rs
- mm2src/coins/utxo/slp.rs
- mm2src/coins/utxo/utxo_standard.rs
- mm2src/coins/z_coin.rs
- mm2src/lp_swap.rs
- mm2src/lp_swap/maker_swap.rs
- mm2src/lp_swap/taker_swap.rs
> Add fallback_swap_contract for ETH/ERC20 and QRC20.

- mm2src/coins/eth.rs
- mm2src/coins/eth/eth_tests.rs
- mm2src/coins/eth/eth_wasm_tests.rs
- mm2src/coins/qrc20.rs
- mm2src/coins/utxo.rs
- mm2src/coins/utxo/qtum.rs
- mm2src/coins/utxo/utxo_common.rs
- mm2src/coins/utxo/utxo_standard.rs
- mm2src/coins/utxo/utxo_tests.rs
> Few important fixes

- mm2src/database/my_orders.rs
- mm2src/lp_ordermatch.rs
> display cancellation reason in order_status RPC

- mm2src/coins/utxo/utxo_common.rs
- mm2src/docker_tests/qrc20_tests.rs
Swaps using segwit addresses in native mode should work now
> Hotfix for segwit swap payment address

- mm2src/coins/utxo.rs
> fix signature for non BCH fork_id coins

- Cargo.lock
- mm2src/coins/utxo.rs
- mm2src/coins/utxo/utxo_common.rs
- mm2src/mm2_bitcoin/keys/Cargo.toml
- mm2src/mm2_bitcoin/keys/src/address.rs
- mm2src/mm2_bitcoin/keys/src/lib.rs
- mm2src/mm2_bitcoin/script/src/script.rs
- mm2src/mm2_tests.rs
> Segwit transaction history

- mm2src/coins/eth.rs
- mm2src/docker_tests.rs
- mm2src/lp_ordermatch.rs
> Hotfix cross-protocol ordermatching when taker uses Sell.

- mm2src/mm2_bitcoin/keys/src/address.rs
- mm2src/mm2_bitcoin/keys/src/cashaddress.rs
- mm2src/mm2_bitcoin/keys/src/lib.rs
> Bitcoin Cash address format for forks

- mm2src/coins/eth.rs
https://github.com/Fantom-foundation/go-lachesis/wiki/Tx-Origination
> fix overflow confirmations eth

- mm2src/common/for_tests.rs
- mm2src/docker_tests.rs
- mm2src/lp_ordermatch.rs
#1053
@tonymorony Could you please test that it matches with the best order now? Please note that:
1. If there are several orders of the same maker the best match is not guaranteed.
2. Order may still match with not the best price from orderbook if the maker doesn't respond for some reason (or incompatible).
> Match taker order with the best price received from makers.

- mm2src/coins/qrc20.rs
- mm2src/coins/utxo.rs
- mm2src/coins/utxo/qtum.rs
- mm2src/coins/utxo/utxo_common.rs
- mm2src/coins/utxo/utxo_standard.rs
- mm2src/common/for_tests.rs
- mm2src/docker_tests.rs
- mm2src/lp_native_dex.rs
- mm2src/lp_ordermatch.rs
- mm2src/lp_ordermatch/best_orders.rs
- mm2src/lp_ordermatch/orderbook_depth.rs
- mm2src/lp_ordermatch/orderbook_rpc.rs
- mm2src/mm2_tests.rs
- mm2src/mm2_tests/structs.rs
- mm2src/ordermatch_tests.rs
#1089 
Please review it very thoroughly. I could have forgotten some places, which this PR also affects.
> Support same orderbook for different tickers.

- mm2src/coins/eth.rs
- mm2src/coins/lp_coins.rs
- mm2src/coins/qrc20.rs
- mm2src/coins/test_coin.rs
- mm2src/coins/utxo.rs
- mm2src/coins/utxo/bch.rs
- mm2src/coins/utxo/qtum.rs
- mm2src/coins/utxo/slp.rs
- mm2src/coins/utxo/utxo_standard.rs
- mm2src/coins/z_coin.rs
- mm2src/coins_activation/src/bch_with_tokens_activation.rs
- mm2src/coins_activation/src/lib.rs
- mm2src/coins_activation/src/platform_coin_with_tokens.rs
- mm2src/coins_activation/src/prelude.rs
- mm2src/coins_activation/src/slp_token_activation.rs
- mm2src/coins_activation/src/token.rs
- mm2src/common/common.rs
- mm2src/common/for_tests.rs
- mm2src/docker_tests.rs
- mm2src/docker_tests/slp_tests.rs
- mm2src/lp_message_service.rs
- mm2src/mm2_tests/structs.rs
- mm2src/notification/telegram/telegram.rs
- mm2src/rpc/dispatcher/dispatcher_v2.rs
> Implement enable_bch_with_tokens RPC. Refactoring

- mm2src/coins/eth.rs
- mm2src/coins/eth/eth_tests.rs
- mm2src/coins/eth/eth_wasm_tests.rs
- mm2src/coins/eth/web3_transport.rs
Implementation of the first step to fix #1102
> Get gas price from all available sources and choose max #1102

- mm2src/coins/utxo.rs
- mm2src/coins/utxo/rpc_clients.rs
- mm2src/common/custom_futures.rs
> Hotfix: Other electrums should work if the first times out

- mm2src/coins/eth.rs
- mm2src/coins/eth/eth_tests.rs
> Use EthCoin::logs_block_range in check_if_my_payment_sent.

- mm2src/coins/utxo.rs
- mm2src/common/jsonrpc_client.rs
fixes #1185 
@cipig can you also check that this doesn't affect the fix on this PR https://github.com/KomodoPlatform/atomicDEX-API/pull/1134
> hotfix for unknown destination address errors showing up

- README.md
> [wip] update readme

- mm2src/mm2.rs
should close: https://github.com/KomodoPlatform/atomicDEX-API/issues/1198
> Remove nxt arg from help

- azure-pipelines-build-stage-job.yml
- azure-pipelines-lint-stage-job.yml
- azure-pipelines-wasm-stage-job.yml
- mm2src/docker_tests/docker_tests_common.rs
> Changes for Linux CI

- mm2src/mm2_tests.rs
> Fix unstable test_update_maker_order_fail test

- azure-pipelines-build-stage-job.yml
- mm2src/docker_tests.rs
- mm2src/docker_tests/docker_tests_common.rs
NB https://github.com/artemii235/komodo_regtest_docker/commit/8e1bc2daa256f4c38419ffeb59a2267e048ac54b
> Use komodod multiarch Docker image in tests. Do not build and upload libmm2 for desktop.

- mm2src/lp_ordermatch.rs
- mm2src/lp_ordermatch/best_orders.rs
- mm2src/mm2_tests.rs
- mm2src/mm2_tests/structs.rs
- mm2src/ordermatch_tests.rs
> Add confirmation settings to orderbook

- docs/DEV_ENVIRONMENT.md
- Podman requirement simplified.
> update podman requirement

- docs/GIT_FLOW_AND_WORKING_PROCESS.md
Signed-off-by: ozkanonur <work@onurozkan.dev>
> [r2r] Add PR naming convention to the docs

- README.md
- docs/DEV_ENVIRONMENT.md
- docs/WASM_BUILD.md
- mm2src/hw_common/src/transport/webusb_driver.rs
- mm2src/lp_swap/my_swaps_storage.rs
- wasm_build/README.md
* Update WASM docs
* Fix pagination by `from_uuid` in `my_recent_swaps` in WASM
> [r2r] Update WASM docs, fix `my_recent_swaps` in WASM

- mm2src/coins/eth.rs
- mm2src/coins/lightning.rs
- mm2src/coins/lp_coins.rs
- mm2src/coins/qrc20.rs
- mm2src/coins/solana.rs
- mm2src/coins/solana/spl.rs
- mm2src/coins/test_coin.rs
- mm2src/coins/utxo/bch.rs
- mm2src/coins/utxo/qtum.rs
- mm2src/coins/utxo/slp.rs
- mm2src/coins/utxo/utxo_common.rs
- mm2src/coins/utxo/utxo_standard.rs
- mm2src/coins/z_coin.rs
- mm2src/lp_swap/maker_swap.rs
- mm2src/lp_swap/taker_swap.rs
> Store maker_coin_htlc_privkey and taker_coin_htlc_privkey as None

- mm2src/mm2_main/build.rs
fixes #1295 
Signed-off-by: Onur Özkan <work@onurozkan.dev>
> [r2r] fix `MM_VERSION` path

- azure-pipelines.yml
#1272 
Tested with this commit https://github.com/KomodoPlatform/atomicDEX-API/commit/f0bb705580af10ef215ee181b8d6dd53a0013967. Build triggered: https://dev.azure.com/ortgma/Marketmaker/_build/results?buildId=7655&view=results
> [r2r] Run clean build on dev every midnight UTC.

- mm2src/coins/eth.rs
- mm2src/coins/qrc20/swap.rs
- mm2src/coins/utxo/utxo_common.rs
- mm2src/mm2_main/src/iris_swap_poc.rs
#1432
https://github.com/KomodoPlatform/atomicDEX-API/issues/1432#issuecomment-1250850653
Assigned P0 because it's urgently required for the upcoming WebDEX release.
> [r2r] Make sha256 secret hash compatible with older ETH swap contract.

- mm2src/mm2_main/Cargo.toml
> [r2r] Set test = true for mm2 bin.

- mm2src/coins/utxo/utxo_builder/utxo_coin_builder.rs
Fixes this https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/2065#issuecomment-1312538505
> [r2r] Don't return an error if a UTXO coin is enabled with `trezor_coin` field

- mm2src/mm2_main/src/lp_swap.rs
Fixes https://github.com/KomodoPlatform/atomicDEX-API/issues/1292
> [r2r] Warn on `No such swap with the uuid`

- Cargo.lock
- mm2src/coins/Cargo.toml
- mm2src/mm2_main/Cargo.toml
> [r2r] Update mocktopus.

- mm2src/coins/tendermint/tendermint_tx_history_v2.rs
> [r2r] Remove "AND tx.height" because it slows down tx_search significantly.

- mm2src/mm2_main/src/rpc.rs
* Spawn `process_json_request` so the RPC requests can be processed asynchronously
> [r2r] Fix WASM RPC handler

- azure-pipelines.yml
- mm2src/coins/z_coin.rs
- mm2src/coins/z_coin/z_rpc.rs
- mm2src/common/common.rs
> [r2r] Add scan_blocks_per_iteration and scan_interval_ms to ZcoinActivationParams.

- mm2src/coins/Cargo.toml
- mm2src/coins/solana.rs
- mm2src/mm2_main/Cargo.toml
- mm2src/mm2_main/tests/docker_tests/mod.rs
> [r2r] ignore solana based tests

- mm2src/coins/solana/spl.rs
- mm2src/coins/tendermint/tendermint_token.rs
- mm2src/coins/utxo/slp.rs
> fix slp token activation

- docs/ANDROID_CROSS_ON_M1_MAC.md
nb: didn't look into the other (potentially outdated) build instructions
> [doc] update mobile build instructions

- Cargo.lock
- deny.toml
- dev-logs/2023-feb/upgrades/axum_core_upgrade_to_0_2_9
- dev-logs/2023-feb/upgrades/bumpalo_upgrade_to_3_12_0
- dev-logs/2023-feb/upgrades/libp2p_upgrade_to_0_45_1
- dev-logs/2023-feb/upgrades/tokio_upgrade_to_1_25_0
- mm2src/coins/Cargo.toml
- mm2src/common/Cargo.toml
- mm2src/floodsub/Cargo.toml
- mm2src/gossipsub/Cargo.toml
- mm2src/mm2_libp2p/Cargo.toml
- mm2src/mm2_libp2p/src/atomicdex_behaviour.rs
- mm2src/mm2_main/Cargo.toml
This PR applies fixes/upgrades on some of the vulnerable dependencies, initializes the dev-log ideology, and fixes potential bug in atomicdex-behaviour p2p network stack.
> [r2r] fix vulnerable dependencies

- mm2src/mm2_main/src/mm2.rs
no changelog entry added since previous PR suppose to do the same thing
> hotfix `env_logger`

- CHANGELOG.md
- Cargo.lock
- mm2src/mm2_bin_lib/Cargo.toml
> bump mm2 to `v1.0.2-beta`

- CHANGELOG.md
- mm2src/coins/tendermint/iris/ethermint_account.rs
- mm2src/coins/tendermint/iris/mod.rs
- mm2src/coins/tendermint/tendermint_coin.rs
ref https://github.com/irisnet/irishub/blob/master/docs/migration/account.md
> iris ethermint compatibility implementation

- CHANGELOG.md
- Cargo.lock
- mm2src/mm2_bin_lib/Cargo.toml
**update `${release-date}` on CHANGELOG before merging this**
blocker for #1771
> bump mm2 to `v1.0.3-beta`

- mm2src/coins/utxo/bch.rs
- mm2src/coins/utxo/qtum.rs
- mm2src/coins/utxo/utxo_standard.rs
- mm2src/mm2_core/src/mm_ctx.rs
- mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
This PR disables the watchtower functionality temporarily due to [#1887](https://github.com/KomodoPlatform/atomicDEX-API/issues/1887). It will be activated again together with the bugfix PR.
> fix(watchtower): disable watchers

- README.md
(before it was not visible :) )
> feat(doc): updated logo to visible in gh light theme

- .github/workflows/validate-mm2-version.yml
- scripts/ci/validate-version-bump.py
helps with https://github.com/KomodoPlatform/atomicDEX-API/issues/1885
> feat(ci): check if version was bumped

- mm2src/coins/lp_coins.rs
- mm2src/mm2_err_handle/src/mm_error.rs
> refactor(chore): improved deduplications

- mm2src/mm2_bitcoin/rpc/src/v1/types/script.rs
- mm2src/mm2_bitcoin/script/src/script.rs
fixes https://github.com/KomodoPlatform/komodo-defi-framework/issues/906
> fix(transactions): add cryptocondition script type

- mm2src/mm2_p2p/src/behaviours/peer_store.rs
> chore(network): add todo note on peer_store

- mm2src/mm2_db/src/indexed_db/drivers/cursor/cursor.rs
https://github.com/KomodoPlatform/komodo-defi-framework/pull/1957#discussion_r1494490024
> fix(indexeddb): set stop on success cursor condition

- .github/workflows/dev-build.yml
- .github/workflows/release-build.yml
closes: https://github.com/KomodoPlatform/komodo-defi-framework/issues/2081
> chore(ci/cd): update dockerhub destination repository

- scripts/ci/upload_artifact.py
Reverts https://github.com/KomodoPlatform/komodo-defi-framework/pull/2158#discussion_r1668594545
> ci(artifact): fix upload bug

- mm2src/mm2_main/src/lp_swap/maker_swap.rs
fixes https://github.com/KomodoPlatform/komodo-defi-framework/issues/2175 https://github.com/KomodoPlatform/komodo-defi-framework/issues/2175#issuecomment-2248502979
> fix(swaps): ensure taker payment spend confirmations

- rust-toolchain.toml
> chore(rust-analyzer): add rust-analyzer into the workspace toolchain

- README.md
Updates an outdated issue address.
> chore(doc): update issue address in README

- mm2src/proxy_signature/src/lib.rs
Prevents creating messages with too long lifetimes.
> fix(proxy-signature): add message lifetime overflows

- mm2src/mm2_main/src/lp_healthcheck.rs
> fix(healthchecks): use safer subtraction on expiration

- mm2src/coins/Cargo.toml
fix mm2_p2p dev build to allow cargo test -p coins
@onur-ozkan
> fix(test): add feature to mm2_p2p dev build

- mm2src/coins/coin_balance.rs
- mm2src/coins/eth.rs
- mm2src/coins/eth/eth_hd_wallet.rs
- mm2src/coins/eth/v2_activation.rs
- mm2src/coins/hd_wallet/address_ops.rs
- mm2src/coins/hd_wallet/coin_ops.rs
- mm2src/coins/hd_wallet/mod.rs
- mm2src/coins/hd_wallet/withdraw_ops.rs
- mm2src/coins/lp_coins.rs
- mm2src/coins/my_tx_history_v2.rs
- mm2src/coins/nft.rs
- mm2src/coins/nft/nft_structs.rs
- mm2src/coins/nft/nft_tests.rs
- mm2src/coins/nft/storage/sql_storage.rs
- mm2src/coins/nft/storage/wasm/wasm_storage.rs
- mm2src/coins/rpc_command/get_new_address.rs
- mm2src/coins/test_coin.rs
- mm2src/coins/utxo.rs
- mm2src/coins/utxo/utxo_common/utxo_tx_history_v2_common.rs
- mm2src/coins/utxo/utxo_hd_wallet.rs
- mm2src/coins/utxo/utxo_tx_history_v2.rs
- mm2src/coins_activation/src/erc20_token_activation.rs
- mm2src/coins_activation/src/eth_with_token_activation.rs
- mm2src/mm2_main/src/lp_swap/maker_swap_v2.rs
- mm2src/mm2_main/src/lp_swap/taker_swap_v2.rs
- mm2src/mm2_main/src/rpc/lp_commands/one_inch/rpcs.rs
- mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
ref issue https://github.com/KomodoPlatform/komodo-defi-framework/issues/2343
> refactor(eth): use trait addr_to_string method instead of old function

- CHANGELOG.md
v2.3.0-beta changelogs were missing, so I added it as well.
> chore(release): add changelog entries for v2.4.0-beta
